### ISSUE TITLE
How to inference using ParellelWaveGAN given a mel spec?

### ISSUE THREAD

**Issue by tsungruihon** [kan-bayashi/ParallelWaveGAN#100]
Would you mind sharing some example to inference using ParellelWaveGAN given a mel spec? Thanks a lot.

**Comment by kan-bayashi** [comment]
See 
- https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
- https://github.com/kan-bayashi/ParallelWaveGAN#how-to-use-pretrained-models

**Comment by tsungruihon** [comment]
OMG... Thank you for such a quick reply. :pray:
