### ISSUE TITLE
How to train ParallelWaveGAN for multi-speaker conditioning

### ISSUE THREAD

**Issue by r406** [kan-bayashi/ParallelWaveGAN#101]
Hi,  would like to train the ParallelWaveGAN with LibriSpeech clean data which has more then 400 speakers with transcripts to be used with tacotron2 synthesizer trained with the same data. Could you please guide on this.

**Comment by kan-bayashi** [comment]
See `egs/VCTK/voc1` for reference.
What we need is that just creating `wav.csp` for training, dev, and eval set.
If you have good alignment, it is better to make `segments` file as well in order to remove the silence.

**Comment by kan-bayashi** [comment]
If I have a time, I will create `egs/libritts/voc1` recipe.

**Comment by r406** [comment]
thanks, I will give a try.  Look forward to your creation of "egs/libritts" recipe

**Comment by kan-bayashi** [comment]
Added in #110

**Comment by SanjaESC** [comment]
Is there a specific reason that there are only PwGAN configurations for multi-speaker models and no MelGAN?

**Comment by kan-bayashi** [comment]
No, this is just because I do not have a lot of gpu slots :(

**Comment by SanjaESC** [comment]
Hmm okay, cause i trained a MelGAN vocoder on my custom dataset using @erogol fork [https://github.com/erogol/ParallelWaveGAN](url) and it was only using around 3-4 GB of VRAM.

**Comment by kan-bayashi** [comment]
Right, I followed the official setting, which does not require large gpu memory. I’m not sure if we use large batch size, the convergence speed will become faster. I’m looking forward to hearing that you successfully trained multi-speaker MelGAN :)

**Comment by SanjaESC** [comment]
[melgan.zip](https://github.com/kan-bayashi/ParallelWaveGAN/files/4351060/melgan.zip)

Here are my first results with MelGAN. I'm currently retraining my tts model. Will then give PwGAN and MelGAN another go.
