### ISSUE TITLE
Mismatch between sample rate in preprocess and what librosa says

### ISSUE THREAD

**Issue by Brechard** [kan-bayashi/ParallelWaveGAN#106]
I am trying to use ParallelWaveGan with the v3 weights. https://drive.google.com/drive/folders/1a5Q2KiJfUQkVFo5Bd1IoYPVicJGnm7EL and in prepocessing the assert function fails because it says the sample rate is 16k but when opening with librosa it says it is 22.05k why is this happening?? If I comment the line and execute everything works but the output audio is like sped up (I guess that is normal).

This is the sample file:
https://drive.google.com/open?id=1M-Bv84EpEMTibMS-HumekhIcgE3TJ99k

**Comment by kan-bayashi** [comment]
Maybe your wav.scp file contains resample command with sox. Could you check it?

**Comment by Brechard** [comment]
I can't find any wav.scp file anywhere

**Comment by kan-bayashi** [comment]
Could you share the code to reproduce your errors?

**Comment by Brechard** [comment]
I didn't change anything in the code, I just followed cloned the repository and did the same thing is said in the how-to-use pretrain models section of the readme, using the weights and sample files I linked in the first comment.

**Comment by kan-bayashi** [comment]
Now I understand your problem.
Your wav file is not 22.05k.

```
$ soxi Ses01F_impro01_F000.wav

Input File     : 'Ses01F_impro01_F000.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:01.95 = 31129 samples ~ 145.917 CDDA sectors
File Size      : 62.3k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

```

`librosa.load` loads wav file as 22.05k by default even if your wav file is 16k.
See the librosa documentation.
https://librosa.github.io/librosa/generated/librosa.core.load.html

**Comment by Brechard** [comment]
:O what a stupid mistake from my side, sorry and thanks for the help!
