### ISSUE TITLE
by my dataset with ./run.sh script run without error but it didn't create any folder

### ISSUE THREAD

**Issue by ohadianoush** [kan-bayashi/ParallelWaveGAN#113]
i create my csv file with (229 lines and its 229 wavs) i know its not enough for quality .
and i replaced my data with LJSpeech downloads data.
after i use ./run.sh ,script run without any error but it didn't create any dir like ( data,dump,exp).
i check my gpu and its working very hard ! but where is directories!

note1: my data text and wavs are in Persian language ( csv is utf-8)
note2: i run script with LJSpeech own orginall data and its work perfect without any problem.

(base) ai@ai-Z390-GAMING-X:~/ParallelWaveGAN/egs/ljspeech/voc1$ ./run.sh 
Stage -1: Data download
Already exists. Skipped.
Stage 0: Data preparation
Successfully split data directory.
Successfully split data directory.
Successfully prepared data.
Stage 1: Feature extraction
Feature extraction start. See the progress via dump/train_nodev/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/eval/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/dev/raw/preprocessing.*.log.
Successfully make subsets.
Successfully make subsets.
Successfully make subsets.
Successfully finished feature extraction of dev set.
Successfully finished feature extraction of eval set.
Successfully finished feature extraction of train_nodev set.
Successfully finished feature extraction.
Statistics computation start. See the progress via dump/train_nodev/compute_statistics.log.
Successfully finished calculation of statistics.
Nomalization start. See the progress via dump/train_nodev/norm/normalize.*.log.
Nomalization start. See the progress via dump/dev/norm/normalize.*.log.
Nomalization start. See the progress via dump/eval/norm/normalize.*.log.
Successfully finished normalization of eval set.
Successfully finished normalization of train_nodev set.
Successfully finished normalization of dev set.
Successfully finished normalization.
Stage 2: Network training
Training start. See the progress via exp/train_nodev_ljspeech_parallel_wavegan.v1/train.log.

**Comment by kan-bayashi** [comment]
What was the problem?
If you found the solutions, please note here.

**Comment by ohadianoush** [comment]
its my mistake & Careless in paths,
sorry :)
but now after traning my persian data set i have a big problem, i create new ticket about that
thanks a lot
