### ISSUE TITLE
The standard file /home/ai/espnet/egs/an4/asr1/../../../tools/kaldi/tools/config/common_path.sh is not present -> Exit!

### ISSUE THREAD

**Issue by ohadianoush** [kan-bayashi/ParallelWaveGAN#117]
hi, sorry for a lot of issues i sent :
~/espnet/egs/an4/asr1# ./run.sh --backend pytorch
The standard file /home/ai/espnet/egs/an4/asr1/../../../tools/kaldi/tools/config/common_path.sh is not present -> Exit!

**Comment by kan-bayashi** [comment]
This is not related to this repository.
Please raise your issue in ESPnet repository.
Anyway, please make sure you have finished the installation before making issue. At least you must read README carefully and search the related issues.

**Comment by ohadianoush** [comment]
oooh, sorry
