### ISSUE TITLE
[HELP] Could you provide your pretrained models?

### ISSUE THREAD

**Issue by kan-bayashi** [kan-bayashi/ParallelWaveGAN#118]
Hey guys, recently I implemented many recipes and added new configs such as melgan. 
I want to try these new configs for each recipe and upload pretrained models, but I have not enough GPUs.
Therefore, if you trained the models which have not yet uploaded as the pretrained model, could you provide them to me?

Thank you for your cooperation in advance.

# TODO

## `parallel_wavegan.v1`
- [x] LibriTTS #124 

## `melgan.v3`
- [ ] JSUT
- [ ] CSMSC
- [ ] CMU Arctic
- [ ] JNAS
- [ ] VCTK
- [ ] LibriTTS

## `parallel_wavegan.v3`

This configuration requires too much time, so low priority.

- [ ] JSUT
- [ ] CSMSC
- [ ] CMU Arctic
- [ ] JNAS
- [ ] VCTK
- [ ] LibriTTS

**Comment by dathudeptrai** [comment]
seems u have done all recipe :))))) or is there a recipe here that u haven't trained yet ?

**Comment by kan-bayashi** [comment]
I will make TODO-like list.

**Comment by rishikksh20** [comment]
Will try on my GPU, by the way, @kan-bayashi this paper (https://arxiv.org/pdf/2005.05106.pdf)  uses similar concept of MelGAN with multiresolutionSTFT loss as used in this repo but with minor tweaking in the base model.

**Comment by kan-bayashi** [comment]
@rishikksh20 Thanks for your info! It seems that the idea is almost the same as this repository. I will check in detail.

**Comment by kan-bayashi** [comment]
I will close this issue.
