### ISSUE TITLE
 InaccessibleTensorError: The tensor 'Tensor conv2d_80/dilation_rate:

### ISSUE THREAD

**Issue by xzm2004260** [kan-bayashi/ParallelWaveGAN#119]
hi @dathudeptrai  @kan-bayashi 
get this error when this line code  “audio = TFMelGANGenerator(**config["generator_params"])(inputs)”  run ，

 InaccessibleTensorError: The tensor 'Tensor("conv2d_80/dilation_rate:0", shape=(2,), dtype=int32)' cannot be accessed here: it is defined in another function or code block. Use return values, explicit Python locals or TensorFlow collections to access it. Defined in: FuncGraph(name=call, id=139867161584976); accessed from: FuncGraph(name=call, id=139867559519064).'

_Originally posted by @xzm2004260 in https://github.com/kan-bayashi/ParallelWaveGAN/pull/112#issuecomment-600636041_

**Comment by kan-bayashi** [comment]
What is the problem?
If you share the solution, it helps other users.

**Comment by kan-bayashi** [comment]
I supported google colab for the notebook. If you have still an issue, please try https://colab.research.google.com/github/kan-bayashi/ParallelWaveGAN/blob/master/notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb
