### ISSUE TITLE
setting audio parameters used ljspeech conf for personal dataset caused errors

### ISSUE THREAD

**Issue by BridgetteSong** [kan-bayashi/ParallelWaveGAN#121]
Great work!!!
i copy the ljspeech/voc1/* in own dir, when i set audio parameters in own dataset, i meet the errors, for example,
sampling_rate: 48000    
fft_size: 4096           
hop_size: 600            
win_length: 2400
parallel_wavegan/models/parallel_wavegan.py line 145
assert c.size(-1) == x.size(-1) 
how should i set right parameters?

**Comment by kan-bayashi** [comment]
You need to modify `upsample_scales` to be `prod(upsample_scales) == hop_size`.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5309099c936fdede809167488d969c8139b2d41f/egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml#L46
