### ISSUE TITLE
combile with parallelWaveGAN and MelGAN

### ISSUE THREAD

**Issue by hyysam** [kan-bayashi/ParallelWaveGAN#122]
Hi，Can you share your train.py which combiles ParallelWaveGAN generator with MelGAN discriminator， thank you！

**Comment by kan-bayashi** [comment]
You do not need to change the script.
Please use `parallel_wavegan.v3.yaml` in `egs/ljspeech/voc/conf`.

**Comment by hyysam** [comment]
Hi，Did you update the pretrain model of this setting？

**Comment by kan-bayashi** [comment]
See https://github.com/kan-bayashi/ParallelWaveGAN#results
