### ISSUE TITLE
How to re-train on music?

### ISSUE THREAD

**Issue by Tylersuard** [kan-bayashi/ParallelWaveGAN#125]
Hello, the examples you give for music sound amazing, the best I've heard from any GAN so far.  How can I train this on my own set of music?

**Comment by kan-bayashi** [comment]
I’ve never tried to train with music, but I think it can be.
(Of course, it is better to consider the feature vector, e.g. F0) 
What you need is to make `wav.scp` for training, development, and evaluation set.
Maybe you can understand the flow by running the one of the recipes.
