### ISSUE TITLE
How can I generate audio from .npy mel-spectogram generated from tacotron2?

### ISSUE THREAD

**Issue by LeeYangseung** [kan-bayashi/ParallelWaveGAN#128]
I saw link below.
- https://github.com/kan-bayashi/ParallelWaveGAN#how-to-use-pretrained-models

It seems to generate sample_gen.wav from sample.wav.
Can you explain how to use .npy mel-spectogram file generated from tacotron2 model to decode audio file(.wav)??.

**Comment by kan-bayashi** [comment]
Try this notebook. I hope you can understand the procedure.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by LeeYangseung** [comment]
Thank you for replying!!!
