### ISSUE TITLE
Colab Notebook taking too long?

### ISSUE THREAD

**Issue by agilebean** [kan-bayashi/ParallelWaveGAN#130]
Thanks to the author for the Google Colab Notebook.
I managed to install all prerequisites without problem.
Yet, executing the cell "Synthesis" hasn't finished after 1h 20m.
This seems to be too long for the short example sentence,
so I would be grateful for any time/GPU!
As sidenote, I'm using Colab Pro that offers an Nividia P100 as GPU.

**Comment by kan-bayashi** [comment]
That is strange.
Let me confirm several questions:

1. Which notebook did you use? [This one]( https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb)?

2. If you use the above notebook, which language did you try?
   English or Japanese or Mandarin

3. If you use the above notebook, which model did you try?
   Text2Mel: Tacotron2 or Transformer or FastSpeech
   Mel2Wav: Parallel WaveGAN or MelGAN

4. If you use the above notebook, what is the your input sentence?

**Comment by agilebean** [comment]
> That is strange.
> Let me confirm several questions:
> 
>     1. Which notebook did you use? [This one](https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb)?
>
yes
>     2. If you use the above notebook, which language did you try?
>        English or Japanese or Mandarin
English
>     3. If you use the above notebook, which model did you try?
>        Text2Mel: Tacotron2 or Transformer or FastSpeech
Tacotron2
>        Mel2Wav: Parallel WaveGAN or MelGAN
Parallel WaveGAN
>     4. If you use the above notebook, what is the your input sentence?
I used the example sentence, and this one:
"Hi cousins, I'm looking forward to our dinner on Friday!"

Just out of curiosity: 
The Colab notebook does not need to clone the parallel-wavegan github repo, correct?

**Comment by kan-bayashi** [comment]
I just tried now, it works.
<img width="1416" alt="スクリーンショット 2020-04-14 午後11 46 41" src="https://user-images.githubusercontent.com/22779813/79238355-3eb7e280-7eaa-11ea-8ab6-d5a008269691.png">
Maybe colab's problem? Please try to reset the runtime.

> Just out of curiosity:
> The Colab notebook does not need to clone the parallel-wavegan github repo, correct?

Yes, in the notebook, we install this repository througth pypi.

**Comment by agilebean** [comment]
ok thanks a lot for testing it.
Could you just tell me how long it took, and which GPU you were using?

Also, I was thinking that it may have to do with some of the path settings?
Are there any absolute paths used in the code?
I installed everything not under /content but /content/sync, that may be the root problem?

**Comment by kan-bayashi** [comment]
Tesla K80.
```
Tue Apr 14 14:53:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0    70W / 149W |    744MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

> Also, I was thinking that it may have to do with some of the path settings?
Are there any absolute paths used in the code?
I installed everything not under /content but /content/sync, that may be the root problem?

I think all of the codes based on relative path.
If you encountered the error like `FileNotFound` or `ImportError`, it may be the problem. But if not, it is no problem.

**Comment by agilebean** [comment]
Thanks a lot.
Then it is must be an issue with Google Colab runtime,
as I don’t get any error messages about FileNotFound etc.

If it only takes 1s with a K80, then the runtime is just clogged (as so often).
