### ISSUE TITLE
cannot preprocess csmsc dataset 

### ISSUE THREAD

**Issue by Dawdleryang** [kan-bayashi/ParallelWaveGAN#135]
Hello Kan-bayashi, 

Thank you for your awesome job, I am trying to run the code for the mandarin dataset, but met the following problem during stage-0 as follows, can help here? Thank you so much. 
.....
Extracting  PhoneLabeling/009997.interval                             OK 
Extracting  PhoneLabeling/009998.interval                             OK 
Extracting  PhoneLabeling/009999.interval                             OK 
Extracting  PhoneLabeling/010000.interval                             OK 
All OK
Successfully finished download.
Stage 0: Data preparation
Successfully split data directory.
Successfully split data directory.
Successfully prepared data.
Stage 1: Feature extraction
Feature extraction start. See the progress via dump/train_nodev/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/dev/raw/preprocessing.*.log.
Feature extraction start. See the progress via dump/eval/raw/preprocessing.*.log.
Successfully make subsets.
Successfully make subsets.
Successfully make subsets.
run.pl: 16 / 16 failed, log is in dump/eval/raw/preprocessing.*.log
run.pl: 16 / 16 failed, log is in dump/train_nodev/raw/preprocessing.*.log
run.pl: 16 / 16 failed, log is in dump/dev/raw/preprocessing.*.log
./run.sh: 3 background jobs are failed.

**Comment by kan-bayashi** [comment]
Could you show me one of the log `dump/eval/raw/preprocessing.*.log`?

**Comment by Dawdleryang** [comment]
# parallel-wavegan-preprocess --config conf/parallel_wavegan.v1.yaml --scp dump/train_nodev/raw/wav.16.scp --segments dump/train_nodev/raw/segments.16 --dumpdir dump/train_nodev/raw/dump.16 --verbose 1 
# Started at Mon May  4 14:28:33 CST 2020
#
/home/xuleiyang/python36/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
^M  0%|          | 0/612 [00:00<?, ?it/s]/bin/sh: 1: sox: not found
/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/utils.py:376: UserWarning: An error happens at loading "cat downloads/CSMSC/Wave/009189.wav | sox -t wav - -c 1 -b 16 -t wav - rate 24000 |"
  'An error happens at loading "{}"'.format(ark_name))
^M  0%|          | 0/612 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/xuleiyang/python36/bin/parallel-wavegan-preprocess", line 11, in <module>
    load_entry_point('parallel-wavegan', 'console_scripts', 'parallel-wavegan-preprocess')()
  File "/home/xuleiyang/local/ParallelWaveGAN/parallel_wavegan/bin/preprocess.py", line 127, in main
    for utt_id, (audio, fs) in tqdm(dataset):
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/tqdm/std.py", line 1127, in __iter__
    for obj in iterable:
  File "/home/xuleiyang/local/ParallelWaveGAN/parallel_wavegan/datasets/scp_dataset.py", line 193, in __getitem__
    fs, audio = self.audio_loader[utt_id]
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/matio.py", line 182, in __getitem__
    array = self.wav_loader[recodeid]
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/utils.py", line 373, in __getitem__
    return self._loader(ark_name)
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/matio.py", line 203, in load_mat
    return _load_mat(fd, offset, slices, endian=endian, as_bytes=as_bytes)
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/matio.py", line 285, in _load_mat
    array = read_kaldi(fd, endian)
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/matio.py", line 362, in read_kaldi
    array, size = read_ascii_mat(fd, return_size=True)
  File "/home/xuleiyang/python36/lib/python3.6/site-packages/kaldiio/matio.py", line 528, in read_ascii_mat
    assert len(string) != 0
AssertionError
# Accounting: time=3 threads=1
# Ended (code 1) at Mon May  4 14:28:36 CST 2020, elapsed time 3 seconds
~

**Comment by kan-bayashi** [comment]
`sox` is not installed. Please install it.

**Comment by Dawdleryang** [comment]
it is already installed, i think
(python36) xuleiyang@WXRG0340:~/local/ParallelWaveGAN/egs/csmsc/voc1$ pip install sox
Requirement already satisfied: sox in /home/xuleiyang/python36/lib/python3.6/site-packages (1.3.7)
(python36) xuleiyang@WXRG0340:~/local/ParallelWaveGAN/egs/csmsc/voc1$ pip install numba
Requirement already satisfied: numba in /home/xuleiyang/python36/lib/python3.6/site-packages (0.49.0)
Requirement already satisfied: numpy>=1.15 in /home/xuleiyang/python36/lib/python3.6/site-packages (from numba) (1.18.3)
Requirement already satisfied: setuptools in /home/xuleiyang/python36/lib/python3.6/site-packages (from numba) (46.1.3)
Requirement already satisfied: llvmlite<=0.33.0.dev0,>=0.31.0.dev0 in /home/xuleiyang/python36/lib/python3.6/site-packages (from numba) (0.32.0)

**Comment by Dawdleryang** [comment]
can share with me the version of numba, llvmlite, librosa you used?

**Comment by kan-bayashi** [comment]
No. See your log.
> ^M 0%| | 0/612 [00:00<?, ?it/s]/bin/sh: 1: sox: not found

It is not installed. You can confirm that `which sox`.

**Comment by kan-bayashi** [comment]
It is better to install sox by root, not as python package.
`sudo apt-get install -y sox`

**Comment by Dawdleryang** [comment]
It solved my problem, thank you very much for your quick response!
