### ISSUE TITLE
How to calculate batch_max_steps

### ISSUE THREAD

**Issue by AyaHamdy** [kan-bayashi/ParallelWaveGAN#137]
Thanks for your effort,
I need to know how i can calculate batch_max_steps for my dataset if the max audio length 6 secs and sampling rate 22050 ?

**Comment by kan-bayashi** [comment]
I have never investigated the effect of batch_max_steps but basically we use around 1 sec for PWG (In the case of 22050 Hz, that is 22050 points, but it must be dividable by hop_size. So the config use 25600 points as default in the case of hop_size=256).
