### ISSUE TITLE
Audio length parameter is not dividable by hop size.

### ISSUE THREAD

**Issue by CODEJIN** [kan-bayashi/ParallelWaveGAN#138]
Hi, thank you for your code. When I checked your code, I found the audio length is 8196, not 8192. Thus this is not dividable by hop length... Is it no problem? It may be a minor issue... 

https://github.com/kan-bayashi/ParallelWaveGAN/blob/b204ccf64aefb7f8fa22e4730632d7943a15f938/egs/ljspeech/voc1/conf/parallel_wavegan.v3.yaml#L92

**Comment by kan-bayashi** [comment]
Oh sorry, This should be fixed.
Thank you for your report!

**Comment by kan-bayashi** [comment]
fixed.
