### ISSUE TITLE
Question. Did you compare ParallelWaveGan or MelGan with WaveRnn in fidelity of the generated samples?

### ISSUE THREAD

**Issue by Kyubyong** [kan-bayashi/ParallelWaveGAN#140]
Hi, thanks for this great repo. 
I was wondering if you compared the performance of ParallelWaveGan or MelGan with other AR models like WaveRNN or WaveGlow. I know they are slower as they are AR models, but I'm curious whether the AR models are inferior to ParallelWaveGan or MelGan in terms of the generated audio samples' quality.

**Comment by kan-bayashi** [comment]
Hi @Kyubyong. 
In ICASSP 2020, Dr. Okamoto in NICT compared the quality between WaveGlow and PWG in both TTS and analysis-synthesis conditions.
I hope you can access the following presentation.
https://2020.ieeeicassp-virtual.org/presentation/poster/transformer-based-text-speech-weighted-forced-attention

P.S. 
I really appreciate you for your great open-source libraries, such as g2p.
Thank you for sharing your great tools!

**Comment by Kyubyong** [comment]
Thanks @kan-bayashi ! I think I need to register first to access the presentation, but I enjoyed the paper, instead. I've read WaveRNN is better than WaveGlow in quality and training time (WaveGlow is painfully slow to train), but do you think WaveRNN is better than PWG as well?

**Comment by kan-bayashi** [comment]
Oh, here is the additional MOS result.
<img width="1553" alt="スクリーンショット 2020-05-11 午後2 01 21" src="https://user-images.githubusercontent.com/22779813/81529801-9a3a9a80-939a-11ea-83b2-7ad447cc02bc.png">
> Picture from https://2020.ieeeicassp-virtual.org/presentation/poster/transformer-based-text-speech-weighted-forced-attention

In terms of quality, I think WaveRNN is a bit better than PWG.
But PWG is the reasonable choice in terms of training speed, inference speed, and the quality.

**Comment by Kyubyong** [comment]
Makes perfect sense! After all, I guess NAR models like PWG or MelGan is a bit underperform AR models, though the former is superior to the latter in training speed. Thanks!
