### ISSUE TITLE
Use pretrained models with Mozilla TTS

### ISSUE THREAD

**Issue by george-roussos** [kan-bayashi/ParallelWaveGAN#148]
Hi all,

I gave the LibriTTS long vocoder a try and I was impressed at how good it can resample. I tried to use it with Mozilla's TTS, but didn't have any luck. Has anyone managed to plug any of the pretrained models in it?

**Comment by G-Wang** [comment]
You need to ensure that the mel features for Mozilla TTS is the same as the features used for LibriTTS vocoder. (I'm going to guess not exactly the same). So you'd need to either re-train Mozilla TTS with ParrallelWaveGAN mel features or vice versa.

**Comment by kan-bayashi** [comment]
Hi. The feature extraction setting might be different (e.g. Mel-range, fft points, hop size, normalization). Therefore, as @G-Wang suggested, you need to match the setting for both models.
