### ISSUE TITLE
How do I convert the tensorflow to tensorflowlite

### ISSUE THREAD

**Issue by swachm** [kan-bayashi/ParallelWaveGAN#149]
Hello,

Thank you for providing the conversion notebook for tensorflow. I am new to ML and was wondering how would i go about converting the tensorflow .pb file to tensorflow lite file .tflite?

Regards,
Manny

I tried the following:
```
import tensorflow
converter = tensorflow.lite.TFLiteConverter.from_saved_model("./checkpoint/tensorflow_generator/")
test = converter.convert()
```

Getting this error:

None is only supported in the 1st dimension. Tensor 'serving_default_input_1' has invalid shape '[None, None, 80]'.

**Comment by kan-bayashi** [comment]
This is out of support of this repository.
Please solve by yourself.
