### ISSUE TITLE
Stage 1 broken w/ custom dataset

### ISSUE THREAD

**Issue by Iamgoofball** [kan-bayashi/ParallelWaveGAN#150]
https://github.com/Iamgoofball/ParallelWaveGAN/tree/mlp_dataset
My dataset is located on this branch at egs/mlp, PR number #147. Branch is a derivative of feature/mb-melgan.
train_nodev processes properly as shown by this image:
![chrome_XkUBmCspQp](https://user-images.githubusercontent.com/4081722/82405261-32c6bf80-9a18-11ea-83a5-2dddd8841a9e.png)
However, dev and eval don't.
The preprocessing log reveals the following:
https://pastebin.com/GSQmXqxT
Is this an issue with my data or an issue with ParallelWaveGAN? It's all 48khz 16-bit PCM wave files located at https://drive.google.com/file/d/1IgTkZiYOk8MGq1ZQ-P2NskAF8ttkIcYp/view?usp=sharing

**Comment by Iamgoofball** [comment]
Solved the issue. Can't have special characters in the file names, some basic pre-processing fixed this.

**Comment by Iamgoofball** [comment]
Spoke too soon, exactly 1 job out of 16 in normalization for dev and eval fails now.
![chrome_Ic3RnRg09t](https://user-images.githubusercontent.com/4081722/82406276-0eb8ad80-9a1b-11ea-80a2-ec14901c3906.png)
Is there a sound length minimum or something? Because that's my only guess here.
failed Eval Norm:
https://pastebin.com/HrnjwZTU
failed Dev Norm:
https://pastebin.com/DsdBv19D

**Comment by kan-bayashi** [comment]
Maybe the number of wavfiles is small compared to the number of split.
Please remove `dump` dir and change `n_jobs` from 16 to 1.
Then, re run from the stage 1 via `./run.sh --stage 1`

**Comment by Iamgoofball** [comment]
Will do, 1 moment.

**Comment by Iamgoofball** [comment]
Here's my notebook setup btw for reference
https://colab.research.google.com/drive/1L6gN93GR9OHd5atRmkuBIPRNHrAfXtg6?usp=sharing
Dropping n_jobs to 1 and doing a re-run from scratch fixed the issue. Unfortunately I had already tossed the workspace as I mistakenly blamed my dataset and needed to re-generate the colab workspace, so I wasn't able to do the stage 1 re-run.

**Comment by kan-bayashi** [comment]
OK. I will close this issue.
