### ISSUE TITLE
Finetune pretrained models for use with Mozilla TTS

### ISSUE THREAD

**Issue by george-roussos** [kan-bayashi/ParallelWaveGAN#151]
Hi everyone,

So I have been experimenting a bit this week and I was able to plug in the pretrained models in the Mozilla TTS Engine and do inference, however, the speech is of course not in the voice of the model and I would guess it is because of different features. Still promising that it did produce something :) 

Now I would like to train a LibriTTS universal vocoder for use with Mozilla TTS and I wanted to ask if anyone would advice for/against using the pretrained weights here and the --resume flag and what I should expect in terms of convergence times. I tried to finetune the LibriTTS long one using one particular voice, whose features I extracted using Mozilla TTS, but after 1 and a half days, it didn't do much. Maybe using the pretrained weights here might hurt it. 

Also, I would like to ask as regards the discriminator when finetuning. Should I leave it enabled? Or calculate that it kicks in later?

Thanks everyone for this work, it is so promising. I cannot believe the quality it gets on CPU 😀

**Comment by kan-bayashi** [comment]
I've never tried with fine-tuning to adjust the feature setting difference.
In the case of standard fine-tuning (say, 100 utts of new speaker), it works well within 50k iters.
And in my case, I updated both generator and discriminator. 
Only updating discriminator caused high frequency noise in my experiments.

**Comment by heibaidaolx123** [comment]
> I've never tried with fine-tuning to adjust the feature setting difference.
> In the case of standard fine-tuning (say, 100 utts of new speaker), it works well within 50k iters.
> And in my case, I updated both generator and discriminator.
> Only updating discriminator caused high frequency noise in my experiments.

Hi, @kan-bayashi , thanks for your execellent work.
When fine-tuning, how did you set the lr?
Thanks.
