### ISSUE TITLE
Does use_causal_conv=True works?

### ISSUE THREAD

**Issue by kwanUm** [kan-bayashi/ParallelWaveGAN#152]
It seems like all config files set use_causal_conv to False. 

As I'm running the model in real-time, I'd like to minimize the future context that the model looks at as much as possible to reduce latency. 

I'm wondering if someone here had a run with use_causal_conv=True, and if so, how did it affect their results.

**Comment by kan-bayashi** [comment]
Internally, I conducted several experiments.
The results became slightly worse than non-causal models but work reasonably.

**Comment by lokesh-vr-17773** [comment]
> Internally, I conducted several experiments. The results became slightly worse than non-causal models but work reasonably.

Any reason why it should be the case, given that the receptive field of both causal and non-causal models is the same?
