### ISSUE TITLE
To Generate My Own English Voice

### ISSUE THREAD

**Issue by Aweminus** [kan-bayashi/ParallelWaveGAN#153]
Thank you for this great project. And I would like to say every detail of your project is perfect,but I still have a problem. 
1.If I want to use my own voice to achieve text-to-speech in English, do I need to train an additional Text2Mel model  besides Vocoder? Do I mean that I only need to train the Vocoder and use the ESPnet real time E2E-TTS model in your Google Drive, then replace the example Vocoder.
2.To train the vocoder, do I need to create my csv file like LJSpeech?
Thanks!

**Comment by Aweminus** [comment]
And to train the vocoder, do I need to create my csv file like LJSpeech?

**Comment by kan-bayashi** [comment]
1. You need to train both models. Maybe adaptation with a small amount of utterances and pretrained model will work.

2.  See https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md
