### ISSUE TITLE
Question: connecting with espnet

### ISSUE THREAD

**Issue by beckgom** [kan-bayashi/ParallelWaveGAN#155]
I'm trying to merge the inference code of ParallelWaveGAN in espnet's egs run script. 
I got the sample wave file but the sample from the ParallelWaveGAN has slightly higher pitch than that from the GL. 

I set the sample sample rate, fmin, fmax fftsize, hop_length between two model (tacotron & parallelwavegan) 

Did I miss something? or do you have any example code for this?

**Comment by kan-bayashi** [comment]
See https://github.com/kan-bayashi/ParallelWaveGAN#decoding-with-espnet-tts-models-features
Or try https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by kan-bayashi** [comment]
If you have still a problem, please re-open.

**Comment by beckgom** [comment]
should i run apply-cmvn before running the wavegan normalization?

**Comment by kan-bayashi** [comment]
The output of the text2mel model is normalized and the input of the mel2text is assumed to be normalized.
If you use different statistics for each text2mel and mel2wav model, first you should perform apply-cmvn with the inverse option.
(text2mel -> [normalized] -> inverse cmvn -> [denormalized] -> pwg normalize -> [normalized] -> pwg decode -> [waveform])
If you want to run within python, you can use espnet provided python version cmvn.
https://github.com/espnet/espnet/blob/master/espnet/transform/cmvn.py

**Comment by beckgom** [comment]
Thank you for your reply. I'm looking into it.
