### ISSUE TITLE
it seems vocoder has memory leak 

### ISSUE THREAD

**Issue by tzhang001** [kan-bayashi/ParallelWaveGAN#160]
I used mandarin demo (transformer tts & parallel-wavegan) in
 `https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=MoNYASQ-A0cN`

I set device to cpu. I read from file and synthesized wave line by line. The problem is that I found the memory usage keeps growing, which seems a leakage. And I found the leakage is from this line: y = vocoder(z, c).view(-1)
Any comments will be appreciated. Thanks

**Comment by kan-bayashi** [comment]
What is your pytorch version?
Are you performing within `with torch.no_grad():` block?
Does your problem happen when using the same text several times?
e.g. 
```python
while True:
	y = vocoder(z, c).view(-1)
```
The model is itself is not a special one, consists of pytorch's layers.
So if the memory leaking happens, I think it is not my code issue.

**Comment by tzhang001** [comment]
I used pytorch=1.4.0, and did 3 experiments, the result was a little strange:

exp1:  cause memory leaking:
`for line in open('test/input'):
    ln = line.strip().split('\t')
    sent = ln[1]
    with torch.no_grad():
        _start = time.time()
        x = frontend(sent)
        c, _, _ = model.inference(x, inference_args)
        z = torch.randn(1, 1, c.size(0) * config["hop_size"]).to(device)
        c = torch.nn.ReplicationPad1d(
            config["generator_params"]["aux_context_window"])(c.unsqueeze(0).transpose(2, 1))
        y = vocoder(z, c).view(-1)`

exp2:  just did with the same text, no problem:
`for line in open('test/input'):
    ln = line.strip().split('\t')
    sent = ln[1]
    with torch.no_grad():
        _start = time.time()
        x = frontend(sent)
        c, _, _ = model.inference(x, inference_args)
        z = torch.randn(1, 1, c.size(0) * config["hop_size"]).to(device)
        c = torch.nn.ReplicationPad1d(
            config["generator_params"]["aux_context_window"])(c.unsqueeze(0).transpose(2, 1))
        while True:
            y = vocoder(z, c).view(-1)`

exp3: same as exp1, except removing the code "y = vocoder(z, c).view(-1)", no problem:
`for line in open('test/input'):
    ln = line.strip().split('\t')
    sent = ln[1]
    with torch.no_grad():
        _start = time.time()
        x = frontend(sent)
        c, _, _ = model.inference(x, inference_args)
        z = torch.randn(1, 1, c.size(0) * config["hop_size"]).to(device)
        c = torch.nn.ReplicationPad1d(
            config["generator_params"]["aux_context_window"])(c.unsqueeze(0).transpose(2, 1))`

It seems the problem happened when executing the line with different input objects

**Comment by kan-bayashi** [comment]
Thank you for your report.
Could you also check with different pytorch version?

**Comment by tzhang001** [comment]
yes, torch 1.0.1 is OK. And torch 1.4 or 1.5 caused memory leaking.

**Comment by kan-bayashi** [comment]
Thanks. 
Then, I have no idea to fix this issue because it seems pytorch issue.
Current solution is to avoid using 1.4 or 1.5.

**Comment by kan-bayashi** [comment]
If you want to use only cpu, it is worthwhile to check cpu build version (Not sure there is a difference).

**Comment by chazo1994** [comment]
> I used mandarin demo (transformer tts & parallel-wavegan) in
> `https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=MoNYASQ-A0cN`
> 
> I set device to cpu. I read from file and synthesized wave line by line. The problem is that I found the memory usage keeps growing, which seems a leakage. And I found the leakage is from this line: y = vocoder(z, c).view(-1)
> Any comments will be appreciated. Thanks
@tzhang001 Could you share your experiment with CPU mode, how is the latency in compared to GPU and compare with Waveglow.

**Comment by kan-bayashi** [comment]
@chazo1994 For the speed, please refer README.
https://github.com/kan-bayashi/ParallelWaveGAN#speed

**Comment by kan-bayashi** [comment]
I will close this issue.

**Comment by chazo1994** [comment]
@kan-bayashi  I'm sory, I asked a non clear question. I mean Performance in comparision with Waveglow on GPU and CPU.
