### ISSUE TITLE
WARNING: Dataset in hdf5 file already exists. recreate dataset in hdf5.

### ISSUE THREAD

**Issue by hadaev8** [kan-bayashi/ParallelWaveGAN#163]
Is this ok to have this warning?

**Comment by kan-bayashi** [comment]
It depends on you.
This means that you re-run stage 1 and use the same `dumpdir`.
Then the script overwrites the already existing feature vector.
If you are aware of this, that is no problem.
If you do not want to overwrite, please change the `dumpdir`.

**Comment by hadaev8** [comment]
It hapens if i use preprocess first time on dir without hdf5 files

**Comment by kan-bayashi** [comment]
Really? What is your recipe?
If you use your own recipe, please check the utt_id (the first column of wav.scp) is not duplicated.

**Comment by hadaev8** [comment]
I used parallel_wavegan.v1.yaml
Not sure what goes wrong, i switched to npy in order to start train without warnings.

**Comment by kan-bayashi** [comment]
No. npy case is the same.
It will overwrite the file without warning.
Maybe you have the same utt_id in the train, dev, or eval set.
