### ISSUE TITLE
expend the multi-band prediction to LPCNet

### ISSUE THREAD

**Issue by GuangChen2016** [kan-bayashi/ParallelWaveGAN#165]
Hi, thanks for sharing your pretty good projects. 
Do you have any plan to extend the multi-band prediction to LPCNet? Which may be some different fromthis projects, like multi band linear prediction etc.

[https://arxiv.org/pdf/2005.05551.pdf](url)

**Comment by kan-bayashi** [comment]
Hi. Thank you for your feature request.
This repository focuses on the GAN-based models so LPCnet is out of scope.
If I have the motivation, I may create a new repository.
