### ISSUE TITLE
Any experiments to compare constant or reflective paddings for STFT?

### ISSUE THREAD

**Issue by erogol** [kan-bayashi/ParallelWaveGAN#166]
I am just curious if anyone has done any experiments to compare constant vs reflective stft padding. Or does anyone have any insights for the right settings? I see here 'reflective' padding is being used.

**Comment by dathudeptrai** [comment]
@erogol you mean ReflectionPad1d layer ?

**Comment by erogol** [comment]
> 
> 
> @erogol you mean ReflectionPad1d layer ?

no stft padding for the first and the last frames.

**Comment by kan-bayashi** [comment]
I've never changed the parameter `pad_mode` in `torch.stft` but in my implementation, I used the Hanning window for STFT so I think the padding effect is relatively small.

**Comment by erogol** [comment]
I thought padding would effect the noise in the silences depending on using constant vs reflective. But maybe it is just too much detail.

**Comment by erogol** [comment]
in my experiments reflection seems to work better than constant padding. Closing this now 👍
