### ISSUE TITLE
VCTK Multi-band MelGAN model to tensorflow

### ISSUE THREAD

**Issue by abylouw** [kan-bayashi/ParallelWaveGAN#174]
Thank you for this repository and the models. I am trying to convert the VCTK MB MelGAN model to tensorflow using the notebook example https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb

The example works as is for the ljspeech MelGAN model, but not for the VCTK MB MelGAN model. I get an assertion error here:
```
np.testing.assert_almost_equal(
    y_pytorch[0, 0, :].numpy(),
    y_tensorflow[0, :, 0],
)
```
and I tried the resulting model but I don't get understandable speech. 

Can you give me a pointer on how to change that example notebook in order to convert the VCTK MB MelGAN model to tensorflow?

**Comment by dathudeptrai** [comment]
@abylouw Hi, i'm a contributor contribute that notebook. Let say that notebook don't have Tensorflow implementation of PQMF layer, so you need convert weight from pytorch to tensorflow on melgan part then use its ouput pass to PQMF layer on tensorflow also.

**Comment by kan-bayashi** [comment]
As @dathudeptrai said, you need to implement PQMF.
I recommend using @dathudeptrai's great repository if you want to use tensorflow.
https://github.com/TensorSpeech/TensorflowTTS

**Comment by abylouw** [comment]
@kan-bayashi Thank you, my problem is that I do not have the computing resources to train a MB MelGAN model with the VCTK dataset.

@dathudeptrai I understand that the filter needs to be implemented, my problem is that the MelGAN generators of pytorch vs tensorflow don't output the same values. I load the pretrained VCTK model and use that notebook as an example of doing the conversion, but the two models output differing values on the same input. If I can get them right at this point then I will add the filter.

**Comment by dathudeptrai** [comment]
@abylouw but for ljspeech the notebook worked ?

**Comment by abylouw** [comment]
@dathudeptrai yes, for ljspeech the two models give the same output

**Comment by kan-bayashi** [comment]
@abylouw Please be careful the number of channels of MelGAN output is 4, not 1.
output.reshape(-1) gives wrong results.

**Comment by dathudeptrai** [comment]
Btw, the output of pytorch model will B,4,T while tensorflow is B,T,4 before pqmf

**Comment by abylouw** [comment]
Yes, I saw that and corrected for that, but they still differ significantly
