### ISSUE TITLE
Audio have repeat padding, while spectrogramm reflect, is it right?

### ISSUE THREAD

**Issue by hadaev8** [kan-bayashi/ParallelWaveGAN#179]
It seems to me this is unnecessary inconsistency, do you have certain reasons for this?

**Comment by kan-bayashi** [comment]
I've never changed the pad mode parameter in STFT.
But I used the Hanning window for STFT so I think the padding effect is relatively small.
If you report the effectiveness, that is great.

Related: https://github.com/kan-bayashi/ParallelWaveGAN/issues/166
