### ISSUE TITLE
Train the parallelwavegan for male voice

### ISSUE THREAD

**Issue by roholazandie** [kan-bayashi/ParallelWaveGAN#180]
Is it possible to filter out only male voices from libritts and then use that as the training data for male voice vocoder?
I am looking for a male TTS system, either pretrained or be able to train.

**Comment by kan-bayashi** [comment]
You can find `LibriTTS/SPEAKERS.txt` in LibriTTS.
It includes speaker gender information.
You can filter `wav.scp` not to include female voice.

**Comment by roholazandie** [comment]
Thanks for your answer, I also wanted to know if I filter based on male voice is it going to give me good quality voice?

**Comment by kan-bayashi** [comment]
Not sure but I think the gender-dependent model is not always better, which depends on the corpus.
And it is better to filter the low-quality recording from training data to make it better.

**Comment by kan-bayashi** [comment]
I will close this issue. If you have additional questions, please re-open.
