### ISSUE TITLE
Multi-band MelGAN must have 4 bands?

### ISSUE THREAD

**Issue by poor1017** [kan-bayashi/ParallelWaveGAN#183]
Hi @kan-bayashi 

    Firstly, thanks to your great work!

    I change the mult-band melgan's config, 'generator_params::out_channels' from '4' to '2'. I want to know if I decrease the band num, the audio quality can beccome better.

    But the generated audio seems very strange, it lost the data for some bands.

    Do you encounter the same situation?

Thanks.

**Comment by kan-bayashi** [comment]
If you want to change the number of bands, you need to change the prototype filter of PQMF manually.
(Currently, the parameters are hard coded.)
Try the following notebook to tune the parameters of prototype filter.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/notebooks/filter_design_example.ipynb

**Comment by poor1017** [comment]
Thanks, I will try it.
