### ISSUE TITLE
Support for Kaldi style wav.scp that has pipes

### ISSUE THREAD

**Issue by sonal-ssj** [kan-bayashi/ParallelWaveGAN#189]
Thank you for the wonderful repository. I had a question: Can ParallelWaveGAN support `wav.scp` that has pipes like Kaldi? 

for example,

`cat data/wav.scp`
```
utterance1 -rE ffmpeg -v 8 -f concat -safe 0 -i lists_cat/utt1.txt -f wav -acodec pcm_s16le -|
utterance2 -rE ffmpeg -v 8 -f concat -safe 0 -i lists_cat/utt2.txt -f wav -acodec pcm_s16le -|
```

**Comment by kan-bayashi** [comment]
Yes, it is supported thanks to [kaldiio](https://github.com/nttcslab-sp/kaldiio).
I also use pipe-style wav.scp.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/88a829b5ef923657b4fb590e0614dec5e106a971/egs/template_single_spk/voc1/local/data_prep.sh#L50
