### ISSUE TITLE
How to generate .wav start from Mel-spectrum

### ISSUE THREAD

**Issue by Changlin-Lee** [kan-bayashi/ParallelWaveGAN#193]
I would like to start from my mel-spectrum (.npy form) to generate a .wav file. It seems I can use the code in test folder? Can you provide a script for that case? Thanks

**Comment by kan-bayashi** [comment]
I will share the snippet to decode your npy file.
Before running it, please make sure you have installed this repository.

```bash
# Here, we assume that npy file is saved in /path/to/sample.npy

# First, we need to create npy file list as feats.scp
# The format is `<file_id> <file_path>`
echo "sample /path/to/sample.npy" > feats.scp

# Run decoding with created feats.scp file
parallel-wavegan-decode --feats-scp feats.scp \
	--checkpoint /path/to/checkpoint \
	--outdir test
```

You can download pretrained models from my google drive.
Please check https://github.com/kan-bayashi/ParallelWaveGAN#results

**Comment by Changlin-Lee** [comment]
> I will share the snippet to decode your npy file.
> Before running it, please make sure you have installed this repository.
> 
> ```shell
> # Here, we assume that npy file is saved in /path/to/sample.npy
> 
> # First, we need to create npy file list as feats.scp
> # The format is `<file_id> <file_path>`
> echo "sample /path/to/sample.npy" > feats.scp
> 
> # Run decoding with created feats.scp file
> parallel-wavegan-decode --feats-scp feats.scp \
> 	--checkpoint /path/to/checkpoint \
> 	--outdir test
> ```
> 
> You can download pretrained models from my google drive.
> Please check https://github.com/kan-bayashi/ParallelWaveGAN#results

Thanks a lot

**Comment by Changlin-Lee** [comment]
> > I will share the snippet to decode your npy file.
> > Before running it, please make sure you have installed this repository.
> > ```shell
> > # Here, we assume that npy file is saved in /path/to/sample.npy
> > 
> > # First, we need to create npy file list as feats.scp
> > # The format is `<file_id> <file_path>`
> > echo "sample /path/to/sample.npy" > feats.scp
> > 
> > # Run decoding with created feats.scp file
> > parallel-wavegan-decode --feats-scp feats.scp \
> > 	--checkpoint /path/to/checkpoint \
> > 	--outdir test
> > ```
> > 
> > 
> > You can download pretrained models from my google drive.
> > Please check https://github.com/kan-bayashi/ParallelWaveGAN#results
> 
> Thanks a lot

Hi, I have another question yet. Since I use a Mel-spectrum as input (use the newest VCTK checkpoint on mb-melgan), which size is (80,200) (80 is frequency and 200 is time ), it mentioned me a wrong input, in channel must be 80. But when I try to transpose the Melgan or cut it to (80,80), the result is noise, can you tell me what is the correct input?

**Comment by kan-bayashi** [comment]
The input format is `(num_frames, num_mels)`.
So in your case, (200, 80).
How did you get your mel-spectrogram? 
We need to use the same feature setting and normalization.
I recommend performing analysis-synthesis at first.
See README. https://github.com/kan-bayashi/ParallelWaveGAN#analysis-synthesis
