### ISSUE TITLE
How much data do i need to train a melGAN from scratch?

### ISSUE THREAD

**Issue by Alexey322** [kan-bayashi/ParallelWaveGAN#194]
Hello. 
How much data do i need to train a melGAN from scratch? Will 3 hours be enough to generate speech?

**Comment by kan-bayashi** [comment]
I tried with 1 hour of speech to train from scratch with mb-melgan.
The quality is not so good but not so bad.
(In the case of PWG, it works well with only 1 hour of data).
So I think 3 hours of data is worthwhile to train from scratch.

**Comment by Alexey322** [comment]
@kan-bayashi Thanks. You have already helped me many times. Could you give me your contacts? I would like to ask you a few more questions regarding speech synthesis, possibly for a fee if you are not interested in answering them. I will delete this post after your reply.
