### ISSUE TITLE
[Question] Plans on new VocGAN vocoder

### ISSUE THREAD

**Issue by Craq** [kan-bayashi/ParallelWaveGAN#200]
Hey, thanks for all the great work you're doing. 
Do you have any plans on implementing and experimenting with the newly announced [VocGAN](https://arxiv.org/pdf/2007.15256.pdf)? It is somewhat based on MelGAN with several changes in discriminator architecture and losses, but they were able to outperform both MelGAN and Parallel WaveGAN.

**Comment by kan-bayashi** [comment]
Thank you for your info. I’m busy recently. 
I’ll consider the implementation after finish the other tasks.
