### ISSUE TITLE
Change another vocoder

### ISSUE THREAD

**Issue by YangHan-Morningstar** [kan-bayashi/ParallelWaveGAN#201]
Hey, I have been running the Parallel WaveGAN on my own dataset and it's really wonderful. But at the same time I want to try another advanced vocoder such as melgan.v1.yaml, could you tell me how to use it? Thanks a lot!

**Comment by Alexey322** [comment]
@YangHan-Morningstar you can see usage examples here
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by kan-bayashi** [comment]
You can refer the config files in ljspeech recipe.
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs/ljspeech/voc1/conf
You can copy it and modify some parameters (fs, hop_size, etc.) to match with your dataset.
Then you can specify it with `--conf` option.
e.g. `run.sh --stage 2 --conf conf/<your_modified_config>.yaml`

**Comment by YangHan-Morningstar** [comment]
OK, I'll trying this, thanks a lot!

**Comment by YangHan-Morningstar** [comment]
> @YangHan-Morningstar you can see usage examples here
> https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

I have run this in my gpu successful but thisParallel WaveGAN Project used by sh file and I'm confused about it but the author just told me how to do it and I'm trying the method. Thanks god, it works!

**Comment by YangHan-Morningstar** [comment]
> You can refer the config files in ljspeech recipe.
> https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs/ljspeech/voc1/
> (You can see brief introduction of the config in each header.)
> You can copy it and modify some parameters (fs, hop_size, etc.) to match with your dataset.
> Then you can specify it with `--conf` option.
> e.g. `run.sh --stage 2 --conf conf/<your_modified_config>.yaml`

I have run it successfully in my gpu, Thanks!
