### ISSUE TITLE
Question about upsample layer in ParallelWaveGAN

### ISSUE THREAD

**Issue by dathudeptrai** [kan-bayashi/ParallelWaveGAN#202]
Hi @kan-bayashi, i have a question about upsample layer in PW:

In [link](https://github.com/kan-bayashi/ParallelWaveGAN/blob/6fa601603816d56222b3aa54969f92dbb97b0abd/parallel_wavegan/layers/upsample.py#L98), the Convolution output is 1 and input channels is 1 also. But in [link](https://github.com/kan-bayashi/ParallelWaveGAN/blob/6fa601603816d56222b3aa54969f92dbb97b0abd/parallel_wavegan/layers/upsample.py#L157) tell me that the input channels should be `aux_channels` (=80), can you expained ?, is it a  depthwise convolution. ?. Also based on this [line](https://github.com/kan-bayashi/ParallelWaveGAN/blob/6fa601603816d56222b3aa54969f92dbb97b0abd/parallel_wavegan/layers/upsample.py#L98) the output is 1 channels but in this [line](https://github.com/kan-bayashi/ParallelWaveGAN/blob/6fa601603816d56222b3aa54969f92dbb97b0abd/parallel_wavegan/layers/residual_block.py#L82) the convolution has input = 80 channels ?

One more question :D. As we know in the GAN training, we should keep the capability of G and D atlest equal, in almost research model D is a bit larger than G to make sure it can be classify audio generated is fake or real. But in the PWavegan, G parameters is around 1.5M but D is just 99k params :D. Do we miss something?, when i read the paper, it's clear that the kernel_size and channels of D is equal with G (64).

**Comment by kan-bayashi** [comment]
> In link, the Convolution output is 1 and input channels is 1 also.

This is because the convolution operation in UpsamplingLayer is 2D and Conv1d in [this part](https://github.com/kan-bayashi/ParallelWaveGAN/blob/6fa601603816d56222b3aa54969f92dbb97b0abd/parallel_wavegan/layers/upsample.py#L157) in is 1D.
(The input shape is `(1, 1, C, T)` VS `(1, C, T)`).

> Do we miss something?, when i read the paper, it's clear that the kernel_size and channels of D is equal with G (64).

PWD discriminator is small.  The number of layers of D is much smaller than G (10 VS 30).

**Comment by dathudeptrai** [comment]
@kan-bayashi thanks :)). I just review the code and everything is fine :)).

**Comment by dathudeptrai** [comment]
@kan-bayashi actually, i'm wondering 2 way to implement the upsample, let see bellow:

way1 (yours): [B, C, T] -> (exapand): [B, C, T, 1] -> (conv): [B, C, T * scale, 1] -> (squeeze): [B, C, T * scale]

way2: [B, C, T] -> (exapand): [B, C, 1, T] -> (conv): [B, C', 1, T * scale] -> (squeeze): [B, C', T * scale].

**Comment by kan-bayashi** [comment]
Yes, that is an option.
I followed r9y9 wavenet vocoder implementation.
