### ISSUE TITLE
Text normalization for TTS

### ISSUE THREAD

**Issue by roholazandie** [kan-bayashi/ParallelWaveGAN#205]
Hi,
Our lab is creating a dataset for TTS but we are wondering what are the best text normalization tools out there to help us with cleaning the dataset. If there is no tool is there any guidelines that helps us with that?

**Comment by kan-bayashi** [comment]
Your question is out of the scope of this repository.
You can find the example script in the following repository:
https://github.com/keithito/tacotron/tree/master/text
And it is better to add pause information to be matched with audio.
