### ISSUE TITLE
[Enhancement] Conversion of trainer to iteration-based approach, rather than epoch-based.

### ISSUE THREAD

**Issue by deepconsc** [kan-bayashi/ParallelWaveGAN#209]
Training most of the networks on speech dataset require little time per epoch, but are always hungry for training for at least couple of hundred epochs. 
During the training I've noticed that for around 30 hours of data, mb-melgan needs no more than 1 minute per epoch on 2x Quadro RTX 8000.  But, it suffers from the delay between epochs during which the dataloader creates the new set. 

Changing the epoch-based training to iteration-based training would save up fellow engineers around 15-20% of the training time. After-epoch calculations could be done in parallel (microservice-alike module). 

P.S. would be happy to help you out hack this feature in case you need it.

**Comment by kan-bayashi** [comment]
Is that a problem of `DataLoader`?
