### ISSUE TITLE
[Question] fmin and fmax

### ISSUE THREAD

**Issue by george-roussos** [kan-bayashi/ParallelWaveGAN#211]
Hi. As regards the fmin and fmax values, I would like to ask if anyone has run into any trouble with wrong values producing worse speech. Especially the fmin, if the speaker is female and has a lower f0, is it better to set the fmin to be 0 to cover all the frequency levels, or is it too dangerous?

**Comment by kan-bayashi** [comment]
I saw the paper using 0-8000 Hz.
And I also tried full-band (0-11025 hz for fs = 22050Hz) and worked well.
Consequently, I think you can do it but the improvement may be small.

**Comment by george-roussos** [comment]
Thanks a lot. Interesting that you tried values bigger than 8000. However I was referring to values smaller than 8000 (i.e. 7600) because the paper mentions the range plays a role and the configs on this repo also apply 7400 as the fmax. Is there any specific intuition?

**Comment by kan-bayashi** [comment]
There are some discussions.
https://github.com/espnet/espnet/issues/1192
According to the above issue, we decided to use 80-7600.

**Comment by george-roussos** [comment]
Thanks a lot, this really helps. I always thought 0-8000 was what Google suggested initially, so everyone went with it.
