### ISSUE TITLE
issue about the last layer of PWGAN discriminator

### ISSUE THREAD

**Issue by fantasyHq** [kan-bayashi/ParallelWaveGAN#212]
Hello! When I try apply the WGAN-GP to the PWGAN model, I find there isn't sigmoid or tanh activation in the last layer of discriminator, which make me feel confused. If there isn't activation in the last layer to control the output and keep it in (0,1),how can we use the (1-D(G(z)) )^2  to calculate the  L_adv?

**Comment by kan-bayashi** [comment]
To calculate `(1-D(G(z)) )^2`, we do not need to fix within (0, 1).
But I've never compared the effectiveness of the activation layer. 
If you have some concerns, it is better to investigate it.

**Comment by fantasyHq** [comment]
Thanks for your help! I really appreciate it ,and I will do more investigation about the question!

**Comment by hdmjdp** [comment]
> investigation

@fantasyHq How about the performance of wgan compared to lsgan?
