### ISSUE TITLE
Why not use speaker embedding like wavenet in multi-speaker synthesis?

### ISSUE THREAD

**Issue by Georgehappy1** [kan-bayashi/ParallelWaveGAN#214]

**Comment by kan-bayashi** [comment]
I do not know the reference using WaveNet with speaker embedding.
Could you provide me?

**Comment by Georgehappy1** [comment]
Like in the wavenet implementation provided by r9r9, 
![图片1](https://user-images.githubusercontent.com/44981462/93869856-f923ff00-fcfe-11ea-98a3-00e8769de0b1.png)
Here the global condition features is speaker embedding.

**Comment by kan-bayashi** [comment]
The simple one-hot vector does not improve the performance and limit the input speaker type from my experience. So I do not use it.

**Comment by kan-bayashi** [comment]
https://arxiv.org/abs/2008.05289
This kind of speaker embedding approach is worthwhile to try.

**Comment by Georgehappy1** [comment]
Got it, but actually it doesnt use one-hot vector as speaker embedding. Instead, they use trainable speaker embedding.
![图片2](https://user-images.githubusercontent.com/44981462/93872109-3fc72880-fd02-11ea-82cb-f40d594635d2.png)
![图片3](https://user-images.githubusercontent.com/44981462/93872117-42c21900-fd02-11ea-894b-d0b2eda7239a.png)

**Comment by Georgehappy1** [comment]
> https://arxiv.org/abs/2008.05289
> This kind of speaker embedding approach is worthwhile to try.

yep, this is what i have said. A trainable speaker embedding may be better.

**Comment by kan-bayashi** [comment]
I think we can also use global style token as the unsupervised speaker embedding. 
If you are interested, you can try it.

**Comment by Georgehappy1** [comment]
> I think we can also use global style token (introduced in GST-Tacotron) as the unsupervised speaker embedding.
> If you are interested, you can try it.

Ok, thanks a lot for ur reply.
