### ISSUE TITLE
"multi_band_melgan.v2.yaml" change result

### ISSUE THREAD

**Issue by LLianJJun** [kan-bayashi/ParallelWaveGAN#216]
Hi~

I make the experiment useful with your good code.
As a result of my experiment,
Changing from 'multi_band_melgan.v2.yaml' to the following was much better.
The noise of the synthesized speech has been significantly reduced.
What do you think is the cause of the increase in performance?

Thanks!

generator_params:
`use_weight_norm: False`
discriminator_params:
`use_weight_norm: False`

ADVERSARIAL LOSS SETTING:
`use_feat_match_loss: true`
`lambda_feat_match : 10.0`
generator_optimizer_params:
`amsgrad: false`
discriminator_optimizer_params:
`amsgrad: false`

**Comment by kan-bayashi** [comment]
Could you give me samples?

**Comment by LLianJJun** [comment]
> Could you give me samples?

Can I send samples using e-amil.   Due to the company's security policy...
Please your email address.

**Comment by kan-bayashi** [comment]
Oh you used private dataset. Then it is OK.
Could you provide training curve? I'm interested.

**Comment by LLianJJun** [comment]
![스크린샷 2020-10-06 오전 11 45 48](https://user-images.githubusercontent.com/67306015/95153150-b4ea3180-07c9-11eb-85c2-f778bf1e159f.png)
![스크린샷 2020-10-06 오전 11 45 27](https://user-images.githubusercontent.com/67306015/95153155-b9aee580-07c9-11eb-8a89-4078a0c618ce.png)

**Comment by LLianJJun** [comment]
@kan-bayashi 
Due to the long vacation, the reply was late. Sorry.
I have trained 3M steps, but it seems to have converged to 1M.

![스크린샷 2020-10-06 오전 11 53 01](https://user-images.githubusercontent.com/67306015/95153510-8caf0280-07ca-11eb-8b7e-79e3f665db2c.png)
![스크린샷 2020-10-06 오전 11 53 13](https://user-images.githubusercontent.com/67306015/95153512-8de02f80-07ca-11eb-9ecf-5ace430ca273.png)

**Comment by kan-bayashi** [comment]
Thank you for sharing! 
Now I am training the models with your suggestion.

**Comment by george-roussos** [comment]
Hi, is the weight normalization disabled really giving better results? In the paper it is mentioned there is a metallic sound that only goes away if you do weight normalization.

**Comment by LqNoob** [comment]
@LLianJJun 
According to the above parameter values, I do not get audible synthesized audio. 
Can you give the modified "multi_band_melgan.v2.yaml" file?

**Comment by ahmedalbahnasawy** [comment]
@LqNoob Try this Modified one.
[Modified-MBGAN.txt](https://github.com/kan-bayashi/ParallelWaveGAN/files/5430154/Modified-MBGAN.txt)

**Comment by LqNoob** [comment]
@ahmedalbahnasawy Thank  you!
I will experiment and observe its results later.

**Comment by LLianJJun** [comment]
@ahmedalbahnasawy Thanks

**Comment by Mingrg** [comment]
@LLianJJun  What's the Language you use to synthesize? English? Now I'm facing the same problem, but I use Chinese. I wonder if there is any good mb-melgan config for Chinese.

**Comment by LLianJJun** [comment]
@Mingrg 
I use Korean.
