### ISSUE TITLE
Combine with  Tacotron mel

### ISSUE THREAD

**Issue by billy800413** [kan-bayashi/ParallelWaveGAN#218]
Hi, first thanks for the code. Vocoder(ParallelWaveGAN) can work well alone(mel is from real voice). However, if the mel from Tacotron, the quality of the vocoder results will be slightly reduced. I think the root cause is that "Tacotron's Mel" is somewhat different from the real Mel. When training vocoder, Can we do some data augmentation for the Mel to solve this kind of problem?

**Comment by kan-bayashi** [comment]
That is one of the common issues in TTS.
There are several choices to reduce quality degradation:
- Improve the quality of Tacotron2's outputs (i.e. using different text2mel model)
- Train the vocoder with ground truth aligned (GTA) mel-spectrogram (see Tacotron2 paper)
  But in my experiments, that is costly but the improvement is not so much.
