### ISSUE TITLE
what is the normal range of the loss?

### ISSUE THREAD

**Issue by Welsun** [kan-bayashi/ParallelWaveGAN#221]
First, Thank you for publishing your code!  I use some part of your code and train the model on my own dataset. However, I find that the loss of generator is more than 10 thousand and the loss of discriminator is more than 5K. So, I want to ask  if this is normal or something wrong with my code.
Thanks!

**Comment by kan-bayashi** [comment]
I'm not sure which model you trained.
Please check the figure in 
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#how-to-run-the-recipe

Or you can find tensorboard log in google drive:
https://github.com/kan-bayashi/ParallelWaveGAN#results
e.g. https://drive.google.com/open?id=1wevYP2HQ7ec2fSixTpZIX0sNBtYZJz_I

**Comment by kan-bayashi** [comment]
If you have a further question, please re-open.
