### ISSUE TITLE
Nondeterministic decoding

### ISSUE THREAD

**Issue by joanna-aflr** [kan-bayashi/ParallelWaveGAN#229]
Hi, 

I am getting a different waveform every time I run parallel-wavegan-decode. Where does this nondeterminism come from? I confirmed that the input values in .h5 files in --dumpdir are the same in every run. 

Thank you in advance for your help.

Joanna

**Comment by kan-bayashi** [comment]
If you use parallel waveGAN, the reason is the input noise.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/53d14969089b3d3229fe6bfce221234f25a9d836/parallel_wavegan/models/parallel_wavegan.py#L216
If you fixed seed for the input noise, the decoding will be deterministic.
