### ISSUE TITLE
Mutiband generate special frequency noise

### ISSUE THREAD

**Issue by Miralan** [kan-bayashi/ParallelWaveGAN#236]
I was trying use pqmf and stft loss in your implementaion to implement mutiband hifigan(generator very smiliar with melgan's).
But it seems always a special frequency noise in 2kHz(1/2 4kHz).  Have you encountered a similar situation. 
![Screenshot 2020-11-12 154147](https://user-images.githubusercontent.com/22438318/98909901-66812e80-24fd-11eb-90fd-f98923c16672.png)

**Comment by kan-bayashi** [comment]
I met a similar phenomenon in the middle of the training (See #143).
Did you change the number of bands? If so, did you tune the PQMF parameters?

**Comment by Miralan** [comment]
> I met a similar phenomenon in the middle of the training (See #143).
> Did you change the number of bands? If so, did you tune the PQMF parameters?

I don't change the bands(default 4). I have tried use pdmf to analysis real wav and re-synthesis. It seems work corecrly.
I also mixed generate subbands and real subbands togther(like real_subband_1 + real_subband_2 + generate_subband_3 + real_subband_4) to synthesis wav and found if use generate_subband_2(1-2khz) and generate_subband_3(2-3khz) will cause such phenomenon.

**Comment by Miralan** [comment]
Maybe I need continue to train it up to 1M steps (Currently 200k steps).

**Comment by kan-bayashi** [comment]
> Maybe I need continue to train it up to 1M steps (Currently 200k steps).

Yes. You should check the noise is remaining after 1M steps.

**Comment by Miralan** [comment]
I continued train this model up to 240k steps, the noise disappeared. Training is really helpful!

**Comment by Miralan** [comment]
Add some time domain loss can solve such problem. Continue to train may need a lot of steps to remove this noise.
