### ISSUE TITLE
PWGAN vs. MB-MelGAN, which one has higher reconstruction quality?

### ISSUE THREAD

**Issue by capavrulus** [kan-bayashi/ParallelWaveGAN#237]
It looks like MB-MelGAN is more complicated than PWGAN and it takes more time to train, but the only thing I can see immediately is that it takes less time to synthesize a wave. I'm wondering if these two architectures have similar performance in terms of naturalness, or one is worse than the other? Which one has a theoretically higher capacity?

**Comment by ahmedalbahnasawy** [comment]
@capavrulus PWG is sightly better than MB-Melgan but MB-melgan is 1.5x faster than PWG during inference 👍 .  you might be able to achieve better result with MB-MelGAN with a much smaller architecture than PWG.

**Comment by yt605155624** [comment]
mark
