### ISSUE TITLE
8K audio preprocess

### ISSUE THREAD

**Issue by DabiaoMa** [kan-bayashi/ParallelWaveGAN#238]
What is the recommended fft_size and mel size for 8K audio preprocess? I noticed that when using fft size 1024 and mel size 80, the last few dimensions of mel features are always 0. I guess it is due to the low sample rate of the audio.  While is it normal or not?

**Comment by OnceJune** [comment]
I've tried 8k, fft_size 1024 and mel_size 80 are ok for me. What's your hop size? 100 or 128 or some other value?

**Comment by kan-bayashi** [comment]
I've never tried with 8kHz but why don't you use the same time length?
