### ISSUE TITLE
High frequency artifacts on generated audio.

### ISSUE THREAD

**Issue by deepconsc** [kan-bayashi/ParallelWaveGAN#239]
Hey @kan-bayashi!

I've been testing MB melgan with Fastspeech2 for already a month. 
After many iterations of analyzing output audios, I've noticed that there are some high frequency artifacts near 11khz, nonetheless the mel frequency window is 80-7600. 
As an outcome e2e pipeline makes some 's'-ish letters to sound metallic and distorted. 

Perhaps higher frequency limit would be better for professionally recorded audio?! - To balance lower distorted frequencies with higher frequency useful ones. 

I'm testing 0-16khz window now. 

Any thoughts? 

P.S. eventually metallic sounds over 's'-ish letters come from lower frequencies.

*attaching image from audacity 
![Screen Shot 2020-11-20 at 13 11 04](https://user-images.githubusercontent.com/48494620/99782722-f729c100-2b32-11eb-8284-4d78f7e14e48.png)

**Comment by kan-bayashi** [comment]
Hmm. Actually I’ve never compared the frequency range. It is worthwhile to check it.
And I also met the similar noise with (MB-)MelGAN but the noise will disappear with PWG. Therefore I’m wondering the use of noise input will effective to reduce such a noise.

**Comment by deepconsc** [comment]
I think fastspeech2 is not clever enough to generate 0-16khz with good quality. Maybe some depth & channels tuning might help, but it'd be overengineering. 

MB-Melgan is trained for 3.5 mln iters for now, and basically it doesn't change anything. Fastspeech is at ~1000 epoch for now, but I'll let it train for 1500, maybe 2000, in case there's some improvement.

Might try out PWG. Which config do you suggest to keep compute lower and overcome this high-tone issue? 
And, what if I convert PWG to MB PWG, do you have any predictions on how it'll perform?

**Comment by deepconsc** [comment]
@kan-bayashi I'm testing mb-melgan with 16000 sample rate, but twice the batch size (as reported in paper). And there are a lot of checkboard artifacts, a very noisy 'hitting' sounds near letter 'a'. Any ideas?
