### ISSUE TITLE
log mel spectrum　and  linear　mel spectrum

### ISSUE THREAD

**Issue by burcehan** [kan-bayashi/ParallelWaveGAN#240]
Hi ,thanks for your work,
I found 'np.log10(np.maximum(eps, np.dot(spc, mel_basis.T)))'  in the code ,that use log  mel spectrum,can I choose to use  linear　mel spectrum, log mel spectrum and linear  mel spectrum,which one is better?
Thanks!

**Comment by kan-bayashi** [comment]
I’ve never tried with linear scale and I do not provide such an option.
Please modify the code by yourself.
Since I use mean-var normalization, the result will be similar to the log scale.
