### ISSUE TITLE
Stereo output

### ISSUE THREAD

**Issue by robclouth** [kan-bayashi/ParallelWaveGAN#241]
Firstly, thanks for the work you've put into this project, it's awesome.

How easy do you think it would be to make the output stereo? Would it be a big job for me to update the code to train and generate 2 audio channels instead of 1? This would allow for much richer output.

**Comment by kan-bayashi** [comment]
I've never tried or seen the stereo TTS.
Do you have any references?

**Comment by robclouth** [comment]
It's not for text to speech. I'm using it for music. I don't have any references, I can't find any.

**Comment by kan-bayashi** [comment]
The current implementation does not consider the phase difference between the channels.
Therefore, it is difficult to model a stereo channel without the modification of the code.
