### ISSUE TITLE
error when using own dataset

### ISSUE THREAD

**Issue by chikiuso** [kan-bayashi/ParallelWaveGAN#242]
Hi, I tried to use the own dataset following the template setting instruction, but it failed when running run.sh like this :  

root@mycomputer :~/parawave/egs/cvc/voc1$ sh ./run.sh
./run.sh: 34: utils/parse_options.sh: Syntax error: Bad for loop variable

May I ask is there something I did wrong in the setting? thanks.

**Comment by kan-bayashi** [comment]
What is your environment (OS etc.)?
The script is not made by me (one of the kaldi utils) and I've never met this error.

**Comment by chikiuso** [comment]
sorry for my mistake, I run it in bash instead of sh and it works now thanks.
