### ISSUE TITLE
Input mel to test your pretrained model.

### ISSUE THREAD

**Issue by leijue222** [kan-bayashi/ParallelWaveGAN#243]
Hi, your work is amazing.
In the colab, you also provide a convenient way for people to test.

In your colab example,  the inference is an end to end test for text to wav format.
Because I already had a taco2 model to generate mel, so I want to use your pre-trained Multi-band MelGAN model to improve the audio.

This is an example of my taco2(trained with 22050HZ, two speakers) output mel:

> shape: (80, 1473)
> mel: [[-3.8383071 -3.5090003 -3.5094485 ... -3.22574   -3.5430827 -3.870497 ]
>  [-3.979212  -3.835504  -3.8540187 ... -3.239952  -3.5393054 -3.8938622]
>  [-3.9962664 -3.806649  -3.7073057 ... -3.3155394 -3.5192316 -3.9663544]
>  ...
>  [-3.2914562 -2.1562395 -1.1874298 ... -3.7448845 -3.8534966 -4.0068884]
>  [-3.2986758 -2.090722  -1.1268148 ... -3.7732124 -3.867183  -4.0040016]
> 

I tried using the following code under colab, but failed:
```
from parallel_wavegan.utils import load_model

vocoder = load_model(vocoder_path)
vocoder.remove_weight_norm()
vocoder = vocoder.eval().to(device)

c = np.load("./eval_mel1.npy")
y = vocoder.inference(c)
```
get error of:

> ---->  y = vocoder.inference(c)
> RuntimeError: Given groups=1, weight of size [80, 80, 5], expected input[1, 1473, 84] to have 80 channels, but got 1473 channels instead
> 

Could you tell me some notes about using mel as the multi-band Belgian input?

**Comment by kan-bayashi** [comment]
See docstring.

https://github.com/kan-bayashi/ParallelWaveGAN/blob/53d14969089b3d3229fe6bfce221234f25a9d836/parallel_wavegan/models/melgan.py#L196
