### ISSUE TITLE
How fmin, fmax parameters affect quality?

### ISSUE THREAD

**Issue by Alexey322** [kan-bayashi/ParallelWaveGAN#244]
Hello, please explain how the parameters mel_fmin and mel_fmax in the Fourier transform affect the sound quality? Why do you use 80-7600 instead of 0-12000 in your configs, where you train 24khz? If I understand correctly, the frequencies values outside this range are cut off when the mel matrix is multiplied by the Fourier transform matrix for noise reduce.

I will also immediately ask the question, if you train sampling _rate = 44100, will it be necessary to change the frequency range of the mel spectrogram to 0-22050 in order to completely copy the voice of very high quality(absolutely no any noise) without loss and without cutting out high and low frequencies?

**Comment by kan-bayashi** [comment]
See https://github.com/kan-bayashi/ParallelWaveGAN/issues/211

> I will also immediately ask the question, if you train sampling _rate = 44100, will it be necessary to change the frequency range of the mel spectrogram to 0-22050 in order to completely copy the voice of very high quality(absolutely no any noise) without loss and without cutting out high and low frequencies?

I've never tried 44.1 kHz setting.
It is worthwhile to try expanding the range and using the larger number of mel basis.
