### ISSUE TITLE
[Question] TFGAN vocoder?

### ISSUE THREAD

**Issue by ZDisket** [kan-bayashi/ParallelWaveGAN#245]
Hello, so this paper came out: https://arxiv.org/abs/2011.12206 describing yet another GAN vocoder. But this one alleges to get MelGAN speed with WaveRNN quality by using two discriminators with a modified MelGAN generator.
Thoughts?

**Comment by deepconsc** [comment]
Seems promising, I'm testing multi band adaptation rn.

**Comment by OnceJune** [comment]
has anyone tried multiband tfgan?

**Comment by deepconsc** [comment]
> has anyone tried multiband tfgan?

Yes, it's better than originally proposed mb-melgan.

**Comment by francislata** [comment]
@deepconsc - do you have samples of MB-TFGAN?
