### ISSUE TITLE
Question on【multi-speakers】【self-datasets】 training

### ISSUE THREAD

**Issue by Lukelluke** [kan-bayashi/ParallelWaveGAN#246]
Hi, @kan-bayashi , ur jobs is great!

1. I countered some simple problem during training on myself multi-speaker datasets, which have the same files tree structure as u described in [Read.me](https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md), with 80k wav utterances. However, when i followed there suggestions , and set `num_dev = 100, num_eval = 100`, set `db_root ` to the right path. Then i countered a traceback: **`num_first + num_second must be the same # utts in src .(200 vs 1)`**

  I tried look into shell script, the 200 ==  num_dev + num_eval, and `vs 1`position original point to `num_src_utts=$(wc -l < "${src_segments}")`  ,where `src_segments=${src_dir}/segments` , and `src_scp=${src_dir}/wav.scp`, then i get really puzzled, why it turns out to be only` 1 ` ? There must be some details i missed, **could u please help to point it out?**

***

2. Then, to solve this problem, due to my usage of training pgan vocoder is to apply in Voice Conversion project, and i tried to use `template_single_spk` scripts, and set the `num_dev = 100, num_eval = 100` again, while the file structures the same as multi-speaker task, the train process going on well. 

However i noticed that, in the `dump` files, both `dev & eval` files contains only 100 wavs in .scp files, which separated into four .scp files. But, in the `voc1/data/train_nodev` file, the wav.scp can contain all available wavs in all speakers. **What i confused just: ** Does my setting on this way at this kind of file structure, can train on all the speakers' wavs well? And does it common to observe the dev/eval only contains `num_dev = 100, num_eval = 100` files, despite there are 80k wavs in all speakers' files? **Can other wavs apart of these 200 wavs be used for training PGAN vocoder ?**

Sorry for my poor coding ability, hoping to get any useful suggestion on how to solve these two problems!

All the best,
Luke Huang

**Comment by kan-bayashi** [comment]
> There must be some details i missed, could u please help to point it out?

In the multi-speaker template, we split train, dev, and eval for each speaker.
And then concatenate the train dir of all speakers (dev and eval as well).
Therefore, we assume that at least the number of each speaker utterances > num_dev + num_eval.

**Comment by kan-bayashi** [comment]
> However i noticed that, in the dump files, both dev & eval files contains only 100 wavs in .scp files

This is because you set `num_dev` and `num_eval` to 100.

**Comment by Lukelluke** [comment]
> > However i noticed that, in the dump files, both dev & eval files contains only 100 wavs in .scp files
> 
> This is because you set `num_dev` and `num_eval` to 100.
> You will get three directories in `dump`:
> 
> * `train_nodev`: training data without development data
> * `dev`: development data
> * `eval`: evaluation data

Thank u for ur reply!

And even when i set `num_first = 1` and `num_second = 1 ` , there still have traceback: `num_first + num_second must be the same # utts in src .(2 vs 1)`, which i confirmed that every folder has .wav files > 100 files.

**Comment by kan-bayashi** [comment]
Maybe your root directory includes some garbage directories.
Please check here the found spks are valid.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/53d14969089b3d3229fe6bfce221234f25a9d836/egs/template_multi_spk/voc1/run.sh#L69

**Comment by Lukelluke** [comment]
> > There must be some details i missed, could u please help to point it out?
> 
> In the multi-speaker template, we split train, dev, and eval for each speaker.
> And then concatenate the train dir of all speakers (dev and eval as well).
> Therefore, we assume that at least the number of each speaker utterances > num_dev + num_eval.

Thank you sooooooo much! @kan-bayashi  !

I solved this problem that by print the number of .wav files that each files contains using `for dir in CurDir/*;do ls $dir|wc -l;done` . And surprised to find that one special folder has only  1 files. sorry to disturb u. U r sooooo nice, thank u again! 

***
Above problem all caused by myself, and anyone else counter the same problem can check self dataset~
***


All the best!
Luke Huang
