### ISSUE TITLE
[Question] STFT Loss

### ISSUE THREAD

**Issue by francislata** [kan-bayashi/ParallelWaveGAN#247]
I just want to make sure but is the code associated in [here](https://github.com/kan-bayashi/ParallelWaveGAN/blob/53d14969089b3d3229fe6bfce221234f25a9d836/parallel_wavegan/losses/stft_loss.py#L82) the ideal way to calculate a log spectrogram loss?

I need to define a log spectrogram loss function and I am looking for inspiration.

In addition, I see that a log cutoff of `1e-7`: https://github.com/kan-bayashi/ParallelWaveGAN/blob/53d14969089b3d3229fe6bfce221234f25a9d836/parallel_wavegan/losses/stft_loss.py#L40 has been used. How was this decided?

**Comment by kan-bayashi** [comment]
This is a heuristic value and I did not consider the value so much.
