### ISSUE TITLE
MelGAN can not outperform griffin lim

### ISSUE THREAD

**Issue by FaridHaziyev** [kan-bayashi/ParallelWaveGAN#250]
Hello and thank you for this easy to use tool. I have actually applied MelGAN as vocoder but it does not perform better than griffin-lim algorithm. What could be the possibly reason, should I increase the number of data available? I am using around 30 hours of data. 

At first I have trained setting sampling rate fs=16000 it gave weird voices. (my training data has 16000 sampling rate) 
Then I converted the training data to 22050 and set fs=22050 and trained with that. Then results become nearly as good as the griffin lim algorithm.

**Comment by kan-bayashi** [comment]
Amount of the training data seems enough.
Please consider trying with the other config (e.g. full_band_melgan).

**Comment by FaridHaziyev** [comment]
Thank you very much. I have tried full_band_melgan and it works better
