### ISSUE TITLE
Speech Marks

### ISSUE THREAD

**Issue by genabotpub** [kan-bayashi/ParallelWaveGAN#251]
Hello,

Thank you very much for this project.

I am looking for a way to generate speech marks identifying the boundary and playback duration of each rendered word in milliseconds. 

At the moment we are using a speech segmentation model to achieve that, but are looking for a method to achieve this without the need for the postprocessing.

Would appreciate any advice on the best way to achieve this.

Thank you,
gen

**Comment by kan-bayashi** [comment]
That is not a problem of vocoder.
Please ask the problem in the other place.
