### ISSUE TITLE
Generator audio samples at 100k iterations

### ISSUE THREAD

**Issue by francislata** [kan-bayashi/ParallelWaveGAN#254]
Many of these GAN vocoders here always start with pertaining their corresponding generator up to 100k iterations. I am curious if anyone can upload some audio samples generated from this pertained generator using the auxiliary loss alone.

I want to know if I'm headed to the right direction. Thank you!

**Comment by LLianJJun** [comment]
Usually, prtrained generators produce synthetic sounds with a lot of mechanical sounds.

**Comment by kan-bayashi** [comment]
You can check my google drive.
https://drive.google.com/drive/folders/1q_SUadUjEdbykHsfVxuIM7n6vtzgfK5L?usp=sharing
