### ISSUE TITLE
fmin/fmax for male voices

### ISSUE THREAD

**Issue by gafsd** [kan-bayashi/ParallelWaveGAN#258]
Hello, I am wondering if my problems with finetuning the vocoder are to do with fmin/fmax. I note that I have more trouble with voices that are male/deeper in pitch. Is it possible that the default fmin is too high at 80? Some other project use 50 as fmin for male voices. Should I retrain espnet / vocoder on ljspeech with 0/8000 then finetune on my small dataset?

**Comment by kan-bayashi** [comment]
To the best quality, it is better to match the extraction setting of pretrained model.
But I think it should be working without retraining (Of course it depends on the size of dataset for fine-tuning). Maybe it is better to replace the stats in this case.

**Comment by hadaev8** [comment]
@kan-bayashi 
Why you use such values for fmin and fmax?
Does it make difference with unrestricted spectrograms?

**Comment by gafsd** [comment]
I am retraining from scratch with fmin 0 fmax 8000 to see if it makes a difference. Please wait a week and I will have results for you.

**Comment by kan-bayashi** [comment]
@hadaev8 See https://github.com/kan-bayashi/ParallelWaveGAN/issues/244

**Comment by gafsd** [comment]
I tried retraining all with fmin 0 fmax 8000 and no better... I think it may be data problem with vocoder as LJSpeech is female and higher pitch. Doesn't seem to handle small dataset low pitch male voice well. I need maybe retrain vocoder with low pitch voice large dataset before finetune
