### ISSUE TITLE
MB_MelGAN Training issue 

### ISSUE THREAD

**Issue by gafsd** [kan-bayashi/ParallelWaveGAN#260]
Hello I try train mb melgan with fmin 0 fmax 8000 and steps per iter at 8192. When it starts to train discriminator it train about 4 step and freeze (no error in log but training hangs and GPU memory remains allocated but no utilisation). I am using pytorch 1.8.1 CUDA 11.1 with 1x RTX 3090 on master.

**Comment by OnceJune** [comment]
hang in i/o maybe, mbmelgan need a lot data preprocessing
