### ISSUE TITLE
How to analysis-synthesis with my own pretrained model without pip install?

### ISSUE THREAD

**Issue by youngboy52** [kan-bayashi/ParallelWaveGAN#265]
Hi, Thank you for your code. I trained a PWG model with my own dataset, and I don't know how to analysis-synthesis with my own model. There are some scripts which implements the encode and decode process like MelGAN? Look forward to your reply~

**Comment by kan-bayashi** [comment]
https://github.com/kan-bayashi/ParallelWaveGAN#analysis-synthesis
