### ISSUE TITLE
how to give direclty the melspec.npy file to the multi speaker parallelwavegan?

### ISSUE THREAD

**Issue by vigneshgig** [kan-bayashi/ParallelWaveGAN#266]
Hi, 
   Thanks for the great project, I need some help on fine-tuning the multi-speaker parallelwavegan using synthesizer generated melspec data for a particular audio file. I'm looking for preprocessing step of audio to melspec conversion file. please help out.  where I can change the code to read the melspec data directly.
Instead of audio to melspec conversion I just want to read the melspec npy directly.
Note I already finetuned the model with the audio. but audio quality is not good enough for synthesizer-generated melspec. but for original audio melspec audio quality is good enough. so that's why I planning to train melspec directly from the synthesizer. i hope if we train in this way audio quality will get better.
Thanks, @kan-bayashi 
Vignesh E

**Comment by kan-bayashi** [comment]
https://github.com/kan-bayashi/ParallelWaveGAN#decoding-with-dumped-npy-files
