### ISSUE TITLE
How can I use my favorite text in decoding?

### ISSUE THREAD

**Issue by 2579356425** [kan-bayashi/ParallelWaveGAN#270]
Excuse me,I want to use ParallelWaveGAN to decode the Tacotron2 model and synthesize the audio I want.But I don't know how to use my favorite text while decoding.Could you tell me what should I do?

**Comment by ahmedalbahnasawy** [comment]
@2579356425 kindly check this colab https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
