### ISSUE TITLE
HiFi-GAN tuning

### ISSUE THREAD

**Issue by kan-bayashi** [kan-bayashi/ParallelWaveGAN#278]
## 2021/08/05
- `v1`
  - Follow official setting
  - Mel range in mel loss is different (full vs. 80-7600)
  - Log base in mel loss is different (ln vs. log10)
- `v2`
  - Use STFT loss instead of Mel loss
- `v3`
  - Use STFT loss instead of Mel loss
  - Perform pretraining 100k iters
  - Use StyleMelGAN's optimizer setting
- `v4`
  - Use both STFT loss + Mel loss
  - Perform pretraining 100k iters
  - Use StyleMelGAN's optimizer setting
- `v5`
  - Perform pretraining 100k iters
  - Use StyleMelGAN's optimizer setting
- `v6`
  - Do not include final outputs in feat match loss
- `v7`
  - Do not include final outputs in feat match loss
  - Use same setting in mel loss (range and log basis)
- `v8`
  - Use same setting in mel loss (range and log basis)
- `v9`
  - Do not include final outputs in feat match loss
  - Use same setting in mel loss (range and log basis)
  - Perform pretraining 100k iters
  - Use StyleMelGAN's optimizer setting
- `v10` 
  - Do not include final outputs in feat match loss
  - Use same setting in mel loss (range and log basis)
  - Use StyleMelGAN's optimizer setting

[confs.tar.gz](https://github.com/kan-bayashi/ParallelWaveGAN/files/6942246/confs.tar.gz)

## 2020/08/06
- `v11` 
  - Use same setting in mel loss (range and log basis)
  - Use StyleMelGAN's optimizer setting

**Comment by kan-bayashi** [comment]
2021/08/06
<img width="1575" alt="スクリーンショット 2021-08-06 9 00 35" src="https://user-images.githubusercontent.com/22779813/128436269-bbf32388-f25f-44b2-9bc1-20814edd8c4f.png">
The official optimizer setting does not work.
If we use StyleMelGAN optimizer setting, all models reached good quality around 150k.

**Comment by kan-bayashi** [comment]
## 2021/08/07

<img width="1905" alt="スクリーンショット 2021-08-07 8 25 09" src="https://user-images.githubusercontent.com/22779813/128579760-a5be0f58-5974-423d-9724-6efffa1925fb.png">

Sample at < 100k iters sounds very good.
`v11` sounds the same as `v10`.
Maybe including final outputs in feat match loss is not so a problem.

**Comment by kan-bayashi** [comment]
## 2021/08/09

<img width="1673" alt="スクリーンショット 2021-08-09 8 46 09" src="https://user-images.githubusercontent.com/22779813/128649368-de67b3eb-1c61-4341-9075-98229b3494c9.png">

`v3` / `v4` / `v5` / `v9` / `v10` / `v11` sounds almost the same.
So at least what I can say from the results are
- Pretraining is not essential
- Including final outputs in feat match loss is not so important (both work)

Now I use `v10` as the default setting in the recipe.

[20210809_hifigan_samples.zip](https://github.com/kan-bayashi/ParallelWaveGAN/files/6951643/20210809_hifigan_samples.zip)

**Comment by OnceJune** [comment]
Hi, could you please share the idea of how to design the tuning configs? Thanks in advance.

**Comment by kan-bayashi** [comment]
> Hi, could you please share the idea of how to design the tuning configs? Thanks in advance.

It depends on what you want to check.

**Comment by kan-bayashi** [comment]
## 2021/08/19 

I tested on various dataset, all of them are working well.
- ljspeech
- jsut
- csmsc
- vctk
- libritts (dev is unseen spks)
- 
<img width="1721" alt="スクリーンショット 2021-08-19 14 18 08" src="https://user-images.githubusercontent.com/22779813/130012014-b70b77b8-6469-403b-a743-936ad85bf5d6.png">

Only ljspeech's mel loss is going up but the quality itself is gradually improved.
