### ISSUE TITLE
StyleMelGAN default configuration

### ISSUE THREAD

**Issue by francislata** [kan-bayashi/ParallelWaveGAN#279]
Hi @kan-bayashi ! I have a question about the adversarial loss implementation for your StyleMelGAN. I noticed that original configuration is used. However, you’re using least squares loss, and not hinge loss. Are you planning to use hinge loss for that experiment?

Thanks!

**Comment by kan-bayashi** [comment]
Now tuning but MSE is already good.
I will implement hinge loss option.

**Comment by francislata** [comment]
Lastly, can you give a brief explanation as the average by discriminators was added and why it is set to `False` for StyleMelGAN?

**Comment by kan-bayashi** [comment]
average_by_dicriminators is similar to `lambda_adv`.
There is no lambda parameters in the paper so I decided to use non-averaged one instead of tuning `lambda_adv`.

**Comment by kan-bayashi** [comment]
Hinge loss is supported in #281.
