### ISSUE TITLE
WARNING:root:Not found stats file. Skipped loading.

### ISSUE THREAD

**Issue by r9y9** [kan-bayashi/ParallelWaveGAN#289]
Hi,

I am seeing the warnings with the recent changes (https://github.com/kan-bayashi/ParallelWaveGAN/pull/285) when loading a pre-trained model. Relevant code:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/732baf2a4e91a4aadf6b3efcacce39b1808b1a11/parallel_wavegan/utils/utils.py#L322-L324

In my use case, I use the exact same acoustic features for training 1) text-to-mel prediction model and 2) neural vocoder. So the stats for normalization/de-normalization is not necessary at inference time.

Is it possible to remove this warning? or is it possible to provide a way to suppress this warning?

**Comment by kan-bayashi** [comment]
Sure! I will change this message.

**Comment by kan-bayashi** [comment]
@r9y9 How about #290?

**Comment by r9y9** [comment]
Thanks! It works for me 💯
