### ISSUE TITLE
Question about StyleMelGAN's discriminator setup

### ISSUE THREAD

**Issue by francislata** [kan-bayashi/ParallelWaveGAN#293]
Hi @kan-bayashi! I noticed that in your StyleMelGAN configurations (e.g., [this one](https://github.com/kan-bayashi/ParallelWaveGAN/blob/5359b5cb01ce87453ed3681ec08fba4032401022/egs/libritts/voc1/conf/style_melgan.v1.yaml#L67)), the `downsample_scales` are set to `[4, 4, 4, 1]`. In particular, I noticed that a downsample scale of `1` has been provided. However, [this layer](https://github.com/kan-bayashi/ParallelWaveGAN/blob/5359b5cb01ce87453ed3681ec08fba4032401022/parallel_wavegan/models/melgan.py#L340-L352) takes care of the last `DBlock` as in the paper:

<img width="541" alt="Screenshot 2021-08-11 at 13 21 46" src="https://user-images.githubusercontent.com/51974347/129074625-fad214d2-4722-4e71-b6ee-3129b962d45a.png">

Though the paper does not specify if it's using a kernel size of `5 x 1`, it keeps referring to the same setup as in the Multiband MelGAN case.

If you add that `1` downsample scale, that convolutional layer doesn't seem to be equivalent to the one as in Multiband MelGAN.

What's the reason as to why you've done this?

**Comment by kan-bayashi** [comment]
Thank you for your question.
Maybe this is caused by my misunderstanding :(
There is no clear intension about the structure.

**Comment by shaun95** [comment]
Reviewing the code and the original MB MelGAN paper, perhaps that last downsample scale of 1 is not needed and can be removed. I doubt it will make a difference either way.

**Comment by francislata** [comment]
That's the same thought I have, @shaun95 . I'm closing this now.
