### ISSUE TITLE
Typo: upsample_kernal_sizes -> upsample_kernel_sizes in HiFI-GAN impl. and configs

### ISSUE THREAD

**Issue by r9y9** [kan-bayashi/ParallelWaveGAN#295]
https://github.com/kan-bayashi/ParallelWaveGAN/search?q=upsample_kernal_sizes

In my option, just leaving the typos is okay (assuming nobody cares). If we want to fix it, it would be very nice not to break existing pre-trained models :cry:

**Comment by kan-bayashi** [comment]
OMG I will fix it and consider the good method to load existing model.

**Comment by kan-bayashi** [comment]
#296 may work.

**Comment by r9y9** [comment]
Yeah it should work. Thanks!
