### ISSUE TITLE
RTF variation

### ISSUE THREAD

**Issue by sciai-ai** [kan-bayashi/ParallelWaveGAN#299]
Hi @kan-bayashi 

I have noticed that the RTF varies even when we use manual seeds for both taco2 and pwg. I am wondering where is this randomness coming from which makes the calculation of tensors slower or faster? #291

**Comment by kan-bayashi** [comment]
Hmm. I think it depends on your machine usage.
How much different?

**Comment by r9y9** [comment]
Seems like `parallel-wavegan-decode` is not force-syncronnize CUDA operations. You might want to use `torch.cuda. synchronize`  before and after the inference. Peseudo code will look like:

```py
torch.cuda.synchronize()
start = time.time()
with torch.no_grad():
    # do inference
torch.cuda.synchronize()
elapsed_time = time.time() - start

```

See https://pytorch.org/docs/stable/notes/cuda.html for details.
