### ISSUE TITLE
Question : using Parallelwavgan on slurm using multiple nodes with multiple GPUs

### ISSUE THREAD

**Issue by mmagdygh** [kan-bayashi/ParallelWaveGAN#303]
I am running ParallelWavgan on slurm using nodes = 2 , gpus per node =4 , total gpus = 8
It failed so the big question is " **Does ParallelWavgan support multi nodes**  "? 
I'm sure It's working on single node with 4 gpus perfectly.

**Comment by kan-bayashi** [comment]
Multi node training is not supported.
