### ISSUE TITLE
data label

### ISSUE THREAD

**Issue by inconnu11** [kan-bayashi/ParallelWaveGAN#308]
Hi, why do we need the label file when we train the vocoder? I thought the pair of mel spectrogram and wav file are enough. For example preprocessing Libritts for training pwg,  I am not clear about the role of 'segments' files generated by stage 0.

**Comment by kan-bayashi** [comment]
First, segments file is optional.
Th segments file is used to trim the silence at the beginning and the end of audio.
The long silence affects the quality especially for Parallel WaveGAN since the discriminator cannot distinguish such parts well.

**Comment by inconnu11** [comment]
Okii. Got it and thanks!
