### ISSUE TITLE
hifigan spectral normalization not work

### ISSUE THREAD

**Issue by the-final** [kan-bayashi/ParallelWaveGAN#309]
Visualizing the saved model, it seems that the discriminator does not execute spec norm， when I modified it to the official code and saved it correctly

![374EF1E2-A137-48FC-B83D-503E29E2215E](https://user-images.githubusercontent.com/31150239/143371239-ba9129cd-f04b-4cfc-9798-896e1247d4e0.jpg)

![423BE026-80A1-4E6B-B8D1-C4866FA59E25](https://user-images.githubusercontent.com/31150239/143371563-ee7edb89-9833-49a4-b66e-6982692ffc91.jpg)

https://github.com/kan-bayashi/ParallelWaveGAN/blob/568d8e60684568f43b5123f67d193cc768bbd6c1/parallel_wavegan/models/hifigan.py#L533
https://github.com/jik876/hifi-gan/blob/4769534d45265d52a904b850da5a622601885777/models.py#L196

**Comment by kan-bayashi** [comment]
spectral_norm is only applied to the first scale discriminator.
https://github.com/jik876/hifi-gan/blob/4769534d45265d52a904b850da5a622601885777/models.py#L223

See `follow_officail_norm` option.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/6d4411b65f9487de5ec49dabf029dc107f23192d/parallel_wavegan/models/hifigan.py#L607-L609

**Comment by the-final** [comment]
@kan-bayashi 
the first scale discriminator of the model does not save weight_orig weight_u weight_v. if spectral_norm is applied，these weights should be saved.

**Comment by kan-bayashi** [comment]
Hmm. Let me check in this weekend.

**Comment by kan-bayashi** [comment]
Fixed #409
