### ISSUE TITLE
in StyleMelGAN, the input of block not match 

### ISSUE THREAD

**Issue by yt605155624** [kan-bayashi/ParallelWaveGAN#310]
in inference, the shape of c and x matches:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/6d4411b65f9487de5ec49dabf029dc107f23192d/parallel_wavegan/models/style_melgan.py#L238

but in forward, the shape of c and x not match 
https://github.com/kan-bayashi/ParallelWaveGAN/blob/6d4411b65f9487de5ec49dabf029dc107f23192d/parallel_wavegan/models/style_melgan.py#L142

Does this the design for GAN TTS in espnet,? https://github.com/espnet/espnet/issues/3536#issuecomment-917306178
but here is no segment_size, so , it this a bug?

**Comment by yt605155624** [comment]
solved , the batch_max_steps is  actually 24000(80*300) , which is different with 25500 in pwgan,

**Comment by kan-bayashi** [comment]
Right, you need to match batch_max_steps.
