### ISSUE TITLE
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).

### ISSUE THREAD

**Issue by IrisLhy** [kan-bayashi/ParallelWaveGAN#314]
Sorry for training question. I get an error on the "train.log" when 35406 steps. I set the num_workers=2. Does anyone have ideas about how to solve this problem? Thanks!

**Comment by kan-bayashi** [comment]
Are you using docker?
Please follow the error message (increasing shared memory with `--shm-size` option in docker).
Or if you use huge dataset, it is better to disable allow_cache option.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/6c2248b218ca2d8628132ebf1e953993028b80c5/egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml#L86

**Comment by IrisLhy** [comment]
Thank you very much! The problem has been solved!!!!
