### ISSUE TITLE
what are the changes that are specific to language in vocoder training

### ISSUE THREAD

**Issue by 123srikanth** [kan-bayashi/ParallelWaveGAN#316]
Hi there I want to train parallelWaveGan vocoder for my hindi dataset so I wanted to know what are the changes that are specific to language that I need to make before proceeding further.

**Comment by kan-bayashi** [comment]
Vocoder has no language specific processing at least in this repo.
You do not need to care about it.

**Comment by 123srikanth** [comment]
thank you
