### ISSUE TITLE
Convert MelGAN generator from pytorch to tensorflow - almost no the same

### ISSUE THREAD

**Issue by AliNGatGeeks** [kan-bayashi/ParallelWaveGAN#321]
Hi
when I run the code for converting the pytorch model to Tensorflow I get the almost not the same error! the outputs seem to be the same thogh!
They are similar to 6th decimal! is that ok?

**Comment by kan-bayashi** [comment]
I think no problem.
And if you want to use tensorflow, I recommend using https://github.com/TensorSpeech/TensorFlowTTS.
