### ISSUE TITLE
what is the receipe to train for melgan vocoder

### ISSUE THREAD

**Issue by 123srikanth** [kan-bayashi/ParallelWaveGAN#322]
I have trained a parallelwavegan vocoder earlier but it is taking huge time to generate the output. I want to try by training melgan vocoder does anyone have the receipe for training melgan?

Thanks in advance

**Comment by kan-bayashi** [comment]
See
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md#how-to-run-the-recipe
You can find configs (make sure you need to modify some parameters if you do not use 22.05khz samples)
https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs/ljspeech/voc1/conf

**Comment by 123srikanth** [comment]
thank you @kan-bayashi. Is there any parameter that will reduce my vocoder training period as reduction factor reduced tts training duration

**Comment by kan-bayashi** [comment]
You mean training speed? or inference speed?
