### ISSUE TITLE
Dataset JSUT and JVS

### ISSUE THREAD

**Issue by conceptofmind** [kan-bayashi/ParallelWaveGAN#325]
Hi! 

I had a few questions pertaining to the datasets used:

1. I was wondering if there was any significant overlap between the JSUT and JVS corpora? 
2. Why were only 20 hours of JVS data used instead of the full 30 hours? If there is overlap in the datasets, do you know which sections from JVS should be removed? 
3. Do you have the dataset used for training linked anywhere to download?

I greatly appreciate your help and consideration.

Thank you,

Enrico

**Comment by kan-bayashi** [comment]
I did not prepare jvs recipe in this repo.
Please specify the codes that you mentioned.

**Comment by conceptofmind** [comment]
> I did not prepare jvs recipe in this repo. Please specify the codes that you mentioned.

My apologies for the inconvenience! 

I was reading through this research paper, https://www.isca-speech.org/archive/pdfs/interspeech_2021/mizuta21_interspeech.pdf, which had this specific repository implementation linked. 

I had assumed that the jvs data recipe was constructed in part by you. I will contact one of other researchers listed.

Thank you!
