### ISSUE TITLE
Training StyleMelGan on custom dataset

### ISSUE THREAD

**Issue by skol101** [kan-bayashi/ParallelWaveGAN#329]
Hello again :)

Are lab mono files required to do the training or that step can be skipped using this script https://gist.github.com/kan-bayashi/eceafcd35a2351f5f6bf89a1ccb956e9 ?

**Comment by skol101** [comment]
What if I use vctk + custom dataset with silence removed?

**Comment by kan-bayashi** [comment]
In such a case, the script maybe suitable, you can skip the lab file creation for your trimmed audio.
https://gist.github.com/kan-bayashi/eceafcd35a2351f5f6bf89a1ccb956e9
Note that only wav.scp and segments are needed for the vocoder training.

> Btw, I managed to create mono labels using merlin, but when running further along the script I got the erro in train_nodev_all preprocessing log
> n_fft=2048 is too small for input signal of length=121
> warnings.warn(

Not sure but your audio seems too short, maybe you can filter out.

**Comment by kan-bayashi** [comment]
Wait, I remembered the mixing the directory with segments and one without segments is not supported in this repo's vctk data prep script.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/vctk/voc1/run.sh#L73
Another options are:
a. Reuse dump directories created in espnet https://github.com/kan-bayashi/ParallelWaveGAN/tree/master/egs#run-training-using-espnet2-tts-recipe-within-5-minutes
b. Use template recipe as is (it does not use lab file) and perform trimming in feature extraction stage via https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/template_multi_spk/voc1/conf/parallel_wavegan.v1.yaml#L18

**Comment by skol101** [comment]
I actually posted the warning above, but looks like the error is this:
`29%|██▊       | 4/14 [00:00<00:00, 33.51it/s]
Traceback (most recent call last):
  File "/home/sk/anaconda3/envs/vc/bin/parallel-wavegan-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/parallel_wavegan/bin/preprocess.py", line 182, in main
    np.abs(audio).max() <= 1.0
  File "/home/sk/anaconda3/envs/vc/lib/python3.8/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by kan-bayashi** [comment]
You should check the `audio` array. It seems it was zero-length.

**Comment by skol101** [comment]
Could the issue be that I had to upsample my dataset to 24000 from 22050?

**Comment by kan-bayashi** [comment]
> Should I still run training with trim_silence: true?

If you use silence removed audio, you do not need it.

> Also, a related question when resuming training. I've updated train_max_steps, but not sure how from the start should discriminator start?

If you want to just make the training longer, you do not need to touch `discriminator_train_start_steps`.
Please use default value 100000 steps, which is a generator pretraining.

**Comment by skol101** [comment]
> If you use silence removed audio, you do not need it.
>
Cheers, the issue was that with silenced removed audio training didn't start. I assume you trained vctk styleMelGan on VCTK Corpus with silence, and this option 'trim_silence' was set to false?  

> If you want to just make the training longer, you do not need to touch `discriminator_train_start_steps`. Please use default value 100000 steps, which is a generator pretraining.

I see, so it doesn't apply during finetuning.

**Comment by kan-bayashi** [comment]
> Cheers, the issue was that with silenced removed audio training didn't start. I assume you trained vctk styleMelGan on VCTK Corpus with silence, and this option 'trim_silence' was set to false?

I trained VCTK model with segments (created from .lab file), so the silence trimmed audio is loaded in feature extraction and therefore I did not use trim_silence option.

**Comment by skol101** [comment]
Is segment training must be manually specified ?

**Comment by kan-bayashi** [comment]
Specified here:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/vctk/voc1/run.sh#L91-L96

**Comment by skol101** [comment]
I'm trying to create a vocoder compatible with StarGanv2-VC. The problem I have is that VC model preprocesses dataset in a different way that this repo does, consider following.

`
import torch
import torchaudio

to_mel = torchaudio.transforms.MelSpectrogram(
    n_mels=80, n_fft=2048, win_length=1200, hop_length=300)
mean, std = -4, 4

def preprocess(wave):
    wave_tensor = torch.from_numpy(wave).float()
    mel_tensor = to_mel(wave_tensor)
    mel_tensor = (torch.log(1e-5 + mel_tensor.unsqueeze(0)) - mean) / std
    return mel_tensor
`

**Comment by kan-bayashi** [comment]
You should replace melspectrogram extraction part.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/parallel_wavegan/bin/preprocess.py#L25-L78
You can include mean and std normalization.
Then, remove normalization part.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/template_single_spk/voc1/run.sh#L94-L129

Change `${dumpdir}/hogehoge/norm` -> `${dumpdir}/hogehoge/raw`
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/template_single_spk/voc1/run.sh#L154-L155
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/egs/template_single_spk/voc1/run.sh#L176

**Comment by skol101** [comment]
Cheers for this. Almost there! I did everything as you suggested, including replacing melspectrogram extraction part with preprocess(wave).

When training starts at iteration 0 I get error:
`ParallelWaveGAN/parallel_wavegan/bin/train.py", line 601, in __call__
    c_batch = torch.tensor(c_batch, dtype=torch.float).transpose(2, 1)  # (B, C, T')
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 2`

**Comment by kan-bayashi** [comment]
Please check the shape of outputs of replaced melspectrogram function.
It needs to be like:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/5bef5a0610e5e0d6153b601bbf91c78582260c8f/parallel_wavegan/bin/preprocess.py#L54

**Comment by skol101** [comment]
Thank you! That really helped!
