### ISSUE TITLE
How to use pre-trained model?

### ISSUE THREAD

**Issue by limitforever** [kan-bayashi/ParallelWaveGAN#33]
Hello, I just found "checkpoint-400000steps.pkl" in your google drive,and I want to synthsis Chinese voice with your pretrained csmsc model, but now I don't know how to use it.
  Can you tell me if the pre-trained model could synthesis the mandarin voice,if so,how?
  Thanks all the time!

**Comment by kan-bayashi** [comment]
In the caes of analysis-synthesis, please follow the procedure in `egs/csmsc/voc1/run.sh`.
Here is the minimal code to perform analysis-synthesis.
```bash
# Please make sure you already installed parallel_wavegan
$ pip install parallel_wavegan

# download pretrained models and put them in pretrained_model/ directory
# make sure following items exist
$ ls pretrain_model
  checkpoint-400000steps.pkl    config.yml    stats.h5

# put audio in sample directory to perform analysis-synthesis
$ ls sample/
  sample.wav

# feature extract -> normalize -> decode
$ parallel-wavegan-preprocess \
	--rootdir sample \
	--config pretrain_model/config.yml \
	--dumpdir dump/sample/raw
$ parallel-wavegan-normalize \
	--config pretrain_model/config.yml \
	--rootdir dump/sample/raw \
	--dumpdir dump/sample/norm \
	--stats pretrain_model/stats.h5
$ parallel-wavegan-decode \
	--checkpoint pretrain_model/checkpoint-400000steps.pkl \
	--dumpdir dump/sample/norm \
	--outdir sample
100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 914.19it/s]
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   1 out of   1 | elapsed:    1.2s finished
2019-11-13 13:44:29,574 (normalize:87) INFO: the number of files = 1.
100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 513.13it/s]
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   1 out of   1 | elapsed:    0.6s finished
2019-11-13 13:44:31,229 (decode:91) INFO: the number of features to be decoded = 1.
2019-11-13 13:44:37,074 (decode:105) INFO: loaded model parameters from pretrain_model/checkpoint-400000steps.pkl.
[decode]: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 18.33it/s, RTF=0.0146]
2019-11-13 13:44:37,132 (decode:129) INFO: finished generation of 1 utterances (RTF = 0.015).


# you can check the sample/sample_gen.wav
$ ls sample
  sample.wav    sample_gen.wav
 
```

**Comment by kan-bayashi** [comment]
I updated README.
If you have further question, please re-open this issue.

**Comment by limitforever** [comment]
> In the caes of analysis-synthesis, please follow the procedure in `egs/csmsc/voc1/run.sh`.
> Here is the minimal code to perform analysis-synthesis.
> 
> ```shell
> # Please make sure you already installed parallel_wavegan
> $ pip install parallel_wavegan
> 
> # download pretrained models and put them in pretrained_model/ directory
> # make sure following items exist
> $ ls pretrain_model
>   checkpoint-400000steps.pkl    config.yml    stats.h5
> 
> # put audio in sample directory to perform analysis-synthesis
> $ ls sample/
>   sample.wav
> 
> # feature extract -> normalize -> decode
> $ parallel-wavegan-preprocess \
> 	--rootdir sample \
> 	--config pretrain_model/config.yml \
> 	--dumpdir dump/sample/raw
> $ parallel-wavegan-normalize \
> 	--config pretrain_model/config.yml \
> 	--rootdir dump/sample/raw \
> 	--dumpdir dump/sample/norm \
> 	--stats pretrain_model/stats.h5
> $ parallel-wavegan-decode \
> 	--checkpoint pretrain_model/checkpoint-400000steps.pkl \
> 	--dumpdir dump/sample/norm \
> 	--outdir sample
> 100%|████████████████████████████████████████| 1/1 [00:00<00:00, 914.19it/s]
> [Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
> [Parallel(n_jobs=16)]: Done   1 out of   1 | elapsed:    1.2s finished
> 2019-11-13 13:44:29,574 (normalize:87) INFO: the number of files = 1.
> 100%|████████████████████████████████████████| 1/1 [00:00<00:00, 513.13it/s]
> [Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
> [Parallel(n_jobs=16)]: Done   1 out of   1 | elapsed:    0.6s finished
> 2019-11-13 13:44:31,229 (decode:91) INFO: the number of features to be decoded = 1.
> 2019-11-13 13:44:37,074 (decode:105) INFO: loaded model parameters from pretrain_model/checkpoint-400000steps.pkl.
> [decode]: 100%|███████████████████| 1/1 [00:00<00:00, 18.33it/s, RTF=0.0146]
> 2019-11-13 13:44:37,132 (decode:129) INFO: finished generation of 1 utterances (RTF = 0.015).
> 
> 
> # you can check the sample/sample_gen.wav
> $ ls sample
>   sample.wav    sample_gen.wav
>  
> ```

First of all,thanks for your help.
I tried following your step to use pretraied model,but yet I met some hard problems.

1.In the step"# put audio in sample directory to perform analysis-synthesis",I put one of the CSMSC audio in sample directory,but it raised "AssertionError: sample seems to have a different sampling rate.",I changed the audio sample but it still remains.I'm wondering what kind of sample you put?

2.I met another assertion"AssertionError: Not found any mel files in $dump/train_nodev/raw.".I found it in /parallel_wavegan/datasets/audio_mel_datasets.py line 160, but the function AudioDataset() requires the parameter “audio_query="*-wave.npy" while you provide "*.wav", and you set audio_length_threshold=None, while this judgment condition will jump directly. So I don't know how to solve it, I did'nt find ".npy" files.

it is appreciated that you could provide some suggestions.

**Comment by kan-bayashi** [comment]
The sampling rate is 24k for CSMSC.
You can find this in `config.yml`.
For downsampling, you can try:
`sox -t wav input.wav -c 1 -b 16 -t wav output.wav rate 24000`
Second error is due to the failure of the first process.
It will disappear.

**Comment by kan-bayashi** [comment]
I added online notebook.
Mandarin demo is not yet added but it helps you.
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by limitforever** [comment]
Thank you for your replying.
Yet I  have solved the running error and  got almost the same results as your sample from"https://kan-bayashi.github.io/ParallelWaveGAN/".While a small problem should be noted:in the config.yml,the format should be changed from "npy" to "hdf5" I think.
And I want to ask you another question: we input audio files to the pretrained model,but if I want text-to-speech and input a sentence,can it synthesis an audio?

**Comment by kan-bayashi** [comment]
@limitforever For TTS, we need Text2Mel models such as Tacotron 2.
I added Mandarin TTS demo, please try this notebook. 
https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb
