### ISSUE TITLE
[QUESTION] improving metalic Noise in synthesized speech?

### ISSUE THREAD

**Issue by seastar105** [kan-bayashi/ParallelWaveGAN#333]
Hi, thanks for good repo

I'm using fine-tuned fastspeech2 + gan vocoder trained on libritts. Synthesized speech has some metalic noise.

Is there any way to remove metalic noise without finetuning vocoder on ground-truth aligned mel? 

Example)

https://user-images.githubusercontent.com/30820469/154622169-7f30a72f-61a1-48f6-9449-b66b9b1f2315.mp4

**Comment by kan-bayashi** [comment]
In my experiments, GAN vocoders without noise input causes such a noise when we do not perform fine-tuning with GTA outputs. On the other hand, GAN vocoders with noise input have less such a noise even without fine-tuning. So if you do not want to fine-tune, try PWG or style MelGAN.

**Comment by seastar105** [comment]
@kan-bayashi I tried both PWG, and style MelGAN. It sounds bit better. Thank you!
