### ISSUE TITLE
Any solution for  the bad cases （artifacts）？

### ISSUE THREAD

**Issue by GuangChen2016** [kan-bayashi/ParallelWaveGAN#345]
Some of the synthesized results (about 3% utterances）has some artifacts (noise). In details, the mel-spectrum in corresponding are discontinuous, shown as follows:
![LEEGHJGKZO(@0@F51_LO$XL](https://user-images.githubusercontent.com/23181283/159260665-329b3f4d-a30a-48a6-8503-81e8a0668241.png)

Any suggestions to improve the this?

**Comment by kan-bayashi** [comment]
Discussed in #213
