### ISSUE TITLE
How to train Hifi-GAN in new dataset

### ISSUE THREAD

**Issue by majidAdibian77** [kan-bayashi/ParallelWaveGAN#352]
Hi
I used pretrained hifi-gan as a vocoder and result was good and now I want to train it in my data But I don't know how can I do it. Is there any instruction to train hifi-gan in new data?

**Comment by kan-bayashi** [comment]
Please check this one.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md
