### ISSUE TITLE
Train libriTTS problem

### ISSUE THREAD

**Issue by winddori2002** [kan-bayashi/ParallelWaveGAN#353]
Hi, I tried to train the Parallel WaveGAN on the LibriTTS dataset but confronted some issues.
I wanted to use a sampling rate of 16000 instead of 24000. However, when I tried to use a sampling rate of 16000, the error occurred.
In the preprocessing.log, there was an assertion error "1272_128104_000001_000000 seems to have a different sampling rate.".
I wonder if it is possible to change the sampling rate when I train the model on LibriTTS.

**Comment by kan-bayashi** [comment]
https://github.com/kan-bayashi/ParallelWaveGAN/blob/1df88a3d95fd7a8294f3147578506051a4eb85e9/egs/libritts/voc1/conf/parallel_wavegan.v1.yaml#L9
Change sampling rate in config.

**Comment by winddori2002** [comment]
@kan-bayashi 
Thank you for responding. 
Although I tried to change the sampling_rate in .yaml file, it did not work.
However, it worked when I used the sampling rate of 24000.

**Comment by kan-bayashi** [comment]
Sorry, I was wrong.
Please change this line
https://github.com/kan-bayashi/ParallelWaveGAN/blob/1df88a3d95fd7a8294f3147578506051a4eb85e9/egs/libritts/voc1/local/data_prep.sh#L59
to
https://github.com/kan-bayashi/ParallelWaveGAN/blob/1df88a3d95fd7a8294f3147578506051a4eb85e9/egs/template_single_spk/voc1/local/data_prep.sh#L50
Please use fs=16000.
And then change sampling rate in config.

**Comment by winddori2002** [comment]
Thank you for answering. 
It works now!
