### ISSUE TITLE
how to use apex to parallel-training

### ISSUE THREAD

**Issue by c9412600** [kan-bayashi/ParallelWaveGAN#355]
![image](https://user-images.githubusercontent.com/45963600/163092707-492c95fe-f7e2-498b-a255-27b24655c134.png)
hello, I used 4 gpu cards and used apex to train in parallel, but the result is that each step of training is performed four times, how can I solve it?

**Comment by kan-bayashi** [comment]
This is a problem of tqdm, so the training itself should be working correctly.
Maybe summary log should be only one line.
(You can get correct display by `tail -f /path/to/train.log`.)
