### ISSUE TITLE
How to solve the problem local/data_prep.sh: line 59: nkf: command not found?

### ISSUE THREAD

**Issue by Hu-chengyang** [kan-bayashi/ParallelWaveGAN#357]
Dear Professor:
When I run the csmsc dataset, it comes out with the problem :local/data_prep.sh: line 59: nkf: command not found, and then, i run the command: pip install nkf , and nkf-0.2.0 have successfully installed,however the problem is still exist:local/data_prep.sh: line 59: nkf: command not found. I will appreciate it if you can help me solve this problem,thank you.

**Comment by kan-bayashi** [comment]
Please install nkf command, e.g., apt install nkf

**Comment by Hu-chengyang** [comment]
sorry, but i am not the root, i do not have the permission.

**Comment by kan-bayashi** [comment]
You can install in your local. Please use google.

**Comment by Hu-chengyang** [comment]
Thank you , I will try.
