### ISSUE TITLE
How to modify the distributed in config.yml?

### ISSUE THREAD

**Issue by Hu-chengyang** [kan-bayashi/ParallelWaveGAN#360]
Dear professor:
Thank you for your carefully guidence and I have successfully run the parallelwavegan.However,the distributed in config.yml is false and I want to modify it to true,can you tell me how to modify the distributed?

**Comment by kan-bayashi** [comment]
Please read README at first.
1. Install apex https://github.com/kan-bayashi/ParallelWaveGAN#b-make-virtualenv
2. https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md#:~:text=If%20you%20want%20to%20accelerate,of%20gpus.%0APlease%20be%20careful.

**Comment by Hu-chengyang** [comment]
I am so sorry, but I really do not find distributed, I have added "distributed: true" to the parallel_wavegan.v3.yaml,however in the config.yml it still "distributed: false".

**Comment by Hu-chengyang** [comment]
Dear professor:
Do you mean if I do not install apex, I will not able to use distributed training,so the distributed will be false?

**Comment by kan-bayashi** [comment]
Are you read the document?
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/README.md#how-to-run-the-recipe

**Comment by Hu-chengyang** [comment]
Yes,I find it, I only use one gpu, so the distributed is false.

**Comment by kan-bayashi** [comment]
multi gpu case is also explained. please read carefully.
