### ISSUE TITLE
How to decode with the same results.

### ISSUE THREAD

**Issue by winddori2002** [kan-bayashi/ParallelWaveGAN#365]
Hi, 

I am using ParallelWaveGan to decode from the mel to wav.
However, every time I decode the outputs, the results have small differences. I wonder if I can fix the seed and reproduce the same results when I run the codes. I used the codes like as below in Python.

cmd = ['parallel-wavegan-decode', '--checkpoint', 
    '../checkpoin.pkl',  '--feats-scp', './feats.1.scp', '--normalize-before','--outdir', './']
subprocess.call(cmd)

Thank you.

**Comment by kan-bayashi** [comment]
Adding `torch.manual_seed(your_favorite_seed)` around https://github.com/kan-bayashi/ParallelWaveGAN/blob/d500e3b18b8830684390d5851842ad3bb10946d9/parallel_wavegan/bin/decode.py#L169
