### ISSUE TITLE
Creating a tensor from a list of numpy.ndarrays is extremely slow

### ISSUE THREAD

**Issue by skol101** [kan-bayashi/ParallelWaveGAN#367]
FYI on v 0.5.4. Maybe this has been fixed? 

train.py:600: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811806235/work/torch/csrc/utils/tensor_new.cpp:201.)
  y_batch = torch.tensor(y_batch, dtype=torch.float).unsqueeze(1)  # (B, 1, T)

**Comment by kan-bayashi** [comment]
Than you for your report. Fixed in #367.
