### ISSUE TITLE
job failed unsure why

### ISSUE THREAD

**Issue by luxzia** [kan-bayashi/ParallelWaveGAN#379]
I am using a recipe to create a new multi-speaker model and while trying to train, it dies after one epoch with this warning: 
This overload of addcmul_ is deprecated: addcmul_(Number value, Tensor tensor1, Tensor tensor2)

It's not giving a specific error but that's the only thing I can find near the end of the exp/train_nodev_all_parallel_wavegan.v1/train.log that indicates anything is an issue, so I'm confused as to what is going on.

**Comment by kan-bayashi** [comment]
That is just a warning. You can ignore it.
