### ISSUE TITLE
Question about config 

### ISSUE THREAD

**Issue by Kio829** [kan-bayashi/ParallelWaveGAN#383]
Hi!

What is difference between [parallel_wavegan.v1.yaml](https://github.com/Kio829/ParallelWaveGAN/blob/master/egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml) and [parallel_wavegan.v3.yaml](https://github.com/Kio829/ParallelWaveGAN/blob/master/egs/ljspeech/voc1/conf/parallel_wavegan.v3.yaml)?
I found that parameters are different between them, but I cannot understand why these parameters are so.

**Comment by kan-bayashi** [comment]
See header comment.
https://github.com/Kio829/ParallelWaveGAN/blob/6c2248b218ca2d8628132ebf1e953993028b80c5/egs/ljspeech/voc1/conf/parallel_wavegan.v3.yaml?rgh-link-date=2022-11-24T07%3A49%3A16Z#L4
