### ISSUE TITLE
Analysis or paper of hubert-discrete-hifigan?

### ISSUE THREAD

**Issue by seastar105** [kan-bayashi/ParallelWaveGAN#392]
#388 was merged last week and it seems this PR is for reconstruct speech from hubert discrete symbols, right?

i think this work could be applied directly for any-to-{one, many} voice conversion. is there any reference paper or anlaysis for this work?

**Comment by ftshijt** [comment]
There are a few related works on using discrete units:
- https://arxiv.org/pdf/2107.05604
- https://arxiv.org/pdf/2203.04911
- https://arxiv.org/pdf/2104.00355.pdf
- https://ieeexplore.ieee.org/iel7/9745891/9746004/09746484.pdf
- https://arxiv.org/pdf/2111.07402.pdf

Ours is mostly following the one in https://arxiv.org/pdf/2107.05604
