### ISSUE TITLE
How to select num_taps and beta for PQMF?

### ISSUE THREAD

**Issue by bfs18** [kan-bayashi/ParallelWaveGAN#404]
Hi, thanks for the great repo.
How to select num_taps and beta for PQMF? I tried scipy.signal.kaiserord(100, 1 / (2*4)), however the result is different from the parameter in the code.

**Comment by bfs18** [comment]
62, 9.0 seems conforms to the following equation
num_taps, beta = kaiserord(90, 0.5 / num_subbands * 1.5)

**Comment by kan-bayashi** [comment]
You can check the notebook:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/notebooks/filter_design_example.ipynb
