### ISSUE TITLE
The generated output contains a lot of noise.

### ISSUE THREAD

**Issue by Lanzik** [kan-bayashi/ParallelWaveGAN#410]
I am currently training Multiband-MelGAN and my Text2Mel model is based on FastSpeech2, trained with ESPnet. During synthesis, the model outputs have a lot of noise, even though I am using a checkpoint-50000  and the hyperparameters seem to be fine upon inspection. Everything appears normal in the predictions directory, but I cannot get the expected output during synthesis. I am attaching the Text2Mel and Mel2Wav config files and would appreciate it if you could take a look and let me know if you understand the issue.
[configs.zip](https://github.com/kan-bayashi/ParallelWaveGAN/files/12068799/configs.zip)
[log with 3 generated samples.zip](https://github.com/kan-bayashi/ParallelWaveGAN/files/12069287/log.with.3.generated.samples.zip)

**Comment by kan-bayashi** [comment]
> the model outputs have a lot of noise, even though I am using a checkpoint-50000

step 50000 is still early stage.
See discussion in https://github.com/kan-bayashi/ParallelWaveGAN/issues/143
