### ISSUE TITLE
Upload latest release to PyPI

### ISSUE THREAD

**Issue by tjysdsg** [kan-bayashi/ParallelWaveGAN#417]
Hi, it would be great if someone can upload the latest release to PyPI since it introduces things related to discrete unit vocoder. Thanks

**Comment by kan-bayashi** [comment]
Sorry for the late reply. I forgot to upload the latest version.
I will do it soon.

**Comment by kan-bayashi** [comment]
https://pypi.org/project/parallel-wavegan/0.6.1/
Uploaded.
