### ISSUE TITLE
code error in path "parallel_wavegan/bin/decode.py"

### ISSUE THREAD

**Issue by ZXHY-82** [kan-bayashi/ParallelWaveGAN#419]
I noticed a bug with the code under a certain path: "parallel_wavegan/bin/decode.py".
In line 207 "feats_scp=args.feats_scp,", but the parameter feat_scp is not defined.
I think this "args.feats_scp" maybe "args.scp".
Looking forward to your reply.

**Comment by kan-bayashi** [comment]
Thank you for your report.
I fixed the issue in #420.
