### ISSUE TITLE
strange noise in long continous voice

### ISSUE THREAD

**Issue by audier** [kan-bayashi/ParallelWaveGAN#42]
hi, kan. 
thank you for your great work.
I have tried your work with singing voice, but I found that it can;'t performed as well as in speech for long continous singing voice generation.
There's some bad case, can you give me some ideas for this problem?
![image](https://user-images.githubusercontent.com/37586343/71237437-78357280-233c-11ea-8112-eeccd58a500a.png)

**Comment by kan-bayashi** [comment]
Hi @audier.
Could you share the audio sample?

**Comment by audier** [comment]
https://drive.google.com/file/d/1Vgg1zxktCpGPoaUYb_Nn3_mOBreuo3I8/view?usp=sharing

**Comment by kan-bayashi** [comment]
Thank you for sharing samples!
I'm not sure the clear reason why this has happened.
The ideas which are worthwhile to try are:
- Increase the number of layers to make the receptive field bigger.
- Improve the upsampling layer especially the first conv part to capture the broader context in feature sequence. e.g. stacking the conv layers.

**Comment by audier** [comment]
hi, @kan-bayashi 
I have tried increase the number of layers to make the receptive field bigger, it seems worked but didn't deal the problem completely .
config: 5 stacks, 50 layers
steps: 260k
https://drive.google.com/file/d/1K2vxOnyOqPYMCix18bqfXL4A8xJv0LGP/view?usp=sharing

**Comment by kan-bayashi** [comment]
Thank you for your report.
How do you think the use of additional aux feature? (e.g. F0)

**Comment by audier** [comment]
I have tried concate F0_embedding with mel, but it didn't work well.

**Comment by audier** [comment]
https://drive.google.com/file/d/1TypLuubnzUmsT8Se9BER5F4kQGHgBa9V/view?usp=sharing
step: 350k
f0 dim: 1
feat: [mel, f0]

**Comment by audier** [comment]
https://drive.google.com/file/d/1oo75WvtmqlTV4F3ZFQz_U_OTBMaygg7k/view?usp=sharing
embed f0 to 80 dims with a conv layer.

**Comment by kan-bayashi** [comment]
I see. I consider further ideas.

- Make the batch length longer. If the continuous voice is longer than the batch length, it means that such a long voice is not considered in training.
- Add a long window setting in STFT loss.

**Comment by audier** [comment]
@kan-bayashi thank you for your ideas.
That seems work but not good enough.
It's hard for me to jugde the quality of the generated waves, my ear maybe hurt these days by these waves.
I'm afraid there's some mistake added when I change your code.
Will you try some singing samples with your work? 
That would be a great news for me.

**Comment by kan-bayashi** [comment]
Do you know the free-corpus of singing voice?

**Comment by audier** [comment]
The NUS-48E dataset can be downloaded from [here](https://smcnus.comp.nus.edu.sg/nus-48e-sung-and-spoken-lyrics-corpus/)
