### ISSUE TITLE
How about ParallelWaveGan combine with Melgan?

### ISSUE THREAD

**Issue by dathudeptrai** [kan-bayashi/ParallelWaveGAN#46]
Hi @kan-bayashi, First I would like to thank you for this implementation.

After read ParallelWavegan Paper, I realized there was another paper out at the same time with parallelwavegan as melgan (https://arxiv.org/abs/1910.06711). These 2 papers have very similar ideas but approach with completely different directions and can complement each other. Here is my summary of the two models for you to get an overview:

- ParallelWavegan: 

1. Use noise vector for generator.
2. Use upsampling + conv2d for generator.
3. MultiScale STFT Loss for generator.
4. Radam optimizer.

- MelGan:
1. Don't use noise vector.
2. use transpose-2D with carefully chosen Kernel-size and stride to avoid checkerboard artifact
3. MultiScale Discriminator.
4. Feature matching for Discriminator.
5. Adam

In terms of speed on CPU (melgal consist of 6 layers, parallelwavegan consist 30 layers), melgan faster than parallelwavegan around 7 times.

As u can see, we can combine these 2 model into one :))). Tell me what do u think about that :)). @kan-bayashi

**Comment by kan-bayashi** [comment]
Hi @dathudeptrai, thank you for sharing your interesting idea! It seems that Parallel WaveGAN (PWG) focuses on the auxiliary loss while MelGAN focuses on the adversarial loss. So I think we can integrate MelGAN's discriminator and its adversarial loss to PWG. It is worthwhile to try.

**Comment by dathudeptrai** [comment]
Thank for very fast reply :)) @kan-bayashi . Pls note that MelGan's generator faster than PWG around 10 times, seem that the key component on PWG better than Melgan is just multi scale STFT loss. Melgan use transposeConv and Resblock simultaneous while PWG use 30 layers Resblock after Upsampling input and it seem a little redundancy. BTW, i think on ur implementation PWG, the final layers on generator should be Tanh :))

**Comment by kan-bayashi** [comment]
> Melgan use transposeConv and Resblock simultaneous while PWG use 30 layers Resblock after Upsampling input and it seem a little redundancy. 

I see. We also need to compare them in terms of the sound quality, how do you think about it?

> BTW, i think on ur implementation PWG, the final layers on generator should be Tanh :))

I also wondering whether to use `tanh` for the final layer at first (No info in the PWG paper, I think). Currently, I did not observe clipping so no activation is acceptable. If someone compares the effect, that is nice.

**Comment by dathudeptrai** [comment]
hi @kan-bayashi, about the sound quality, i'm testing both of them on Vietnamese :)), seem that parallel waveGan better than Melgan a bit interms of MOS score (4.0 and 3.7, respectively). But i think if we use multi scale STFT loss for Melgan, It will be as good as parallel wavegan and faster around 10 times. Because i'm focusing on Mobile device, so i prefer Melgan :)). BTW, i think melgan discriminator will help u solve #27 issue :D

**Comment by erogol** [comment]
This update does not include a sample config file I guess?

**Comment by kan-bayashi** [comment]
Not yet. Once I successfully finish, I will make PR.

**Comment by G-Wang** [comment]
Hi @kan-bayashi, wondering if you have any training result samples for MelGan? Does it do as well in audio quality compared to ParallelGan?

**Comment by kan-bayashi** [comment]
I added MelGAN's results.
The results are slightly worse than PWG but seem to be reasonable.
I close this issue.
