### ISSUE TITLE
Training with 16kHz audio

### ISSUE THREAD

**Issue by fosimoes** [kan-bayashi/ParallelWaveGAN#52]
What configuration parameters should I modify in order to train with 16kHz audio?

I intend to work with:
sampling_rate: 16000
fft_size: 512
hop_size: 128

I believe I should also change upsample_scales and stft_loss_params, but I am not sure which values to use....

**Comment by kan-bayashi** [comment]
See arctic config.
https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/egs/arctic/voc1/conf/parallel_wavegan.v1.yaml

In my case, I've not changed your mentioned parameters but it works well.
(You can check the sample in google drive written in README).

Of course, there may be more suitable parameters.
If you share your experiments, that is great.

**Comment by fosimoes** [comment]
The following configuration seem to work:
sampling_rate: 16000 
fft_size: 512 
hop_size: 128 
upsample_scales: [4, 4, 4, 2]

Hope this can lead to a faster inference with still good audio quality.
