### ISSUE TITLE
Resume training info

### ISSUE THREAD

**Issue by cfrancesco** [kan-bayashi/ParallelWaveGAN#53]
Hi,
great repo, very intuitive to use.

Just wanted to suggest to maybe include some information regarding how to resume training, which as far as I can search, it is not documented yet. Given how simple and well managed it is, it's a pity one has to look into the code:)

For reference:
just paste the path to the desired checkpoint in the variable ```resume```  in ```run.sh```

Also, I find that it would be great if both resume and the name of the dataset would be CL variables for ```run.sh```, it would make it even easier to train on your own data.

**Comment by kan-bayashi** [comment]
Thank you for your suggestion.
I added comment for command line options and added example in README (#55).
