### ISSUE TITLE
question: is it a tts model? speech to speech is not supported?

### ISSUE THREAD

**Issue by salisbury-espinosa** [kan-bayashi/ParallelWaveGAN#59]

**Comment by kan-bayashi** [comment]
Do you mean voice conversion? Parallel WaveGAN is a kind of vocoder, so you can use it for not only TTS but also voice conversion.

Actually we already applied this implementation for VC. Please check our paper if you are interested.
https://arxiv.org/abs/1912.06813

**Comment by salisbury-espinosa** [comment]
> Do you mean voice conversion? 
 yes

> Actually we already applied this implementation for VC. Please check our paper if you are interested.

cool! is there a public implementation of this paper or  audio samples?

**Comment by kan-bayashi** [comment]
Please check the following HP.
https://unilight.github.io/Publication-Demos/publications/transformer-vc/
