### ISSUE TITLE
memory when inference

### ISSUE THREAD

**Issue by 11721206** [kan-bayashi/ParallelWaveGAN#70]
I want to know when inference, the memory is ? because I test the result is 1.5G, the model size is 1.44M, I think the memory is too large

**Comment by kan-bayashi** [comment]
It's depends on the length of inputs.
If you want to generate the very long waveform, the required memory size will be bigger.

**Comment by 11721206** [comment]
> It's depends on the length of inputs.
> If you want to generate the very long waveform, the required memory size will be bigger.

when I disable the datasets,and only load model, the memory is 1G. I just think the model size is 1.44M , the loaded model will eat so much memory?

**Comment by kan-bayashi** [comment]
Not sure but this will help you.
https://discuss.pytorch.org/t/gpu-memory-estimation-given-a-network/1713
