### ISSUE TITLE
spectrum not continuos

### ISSUE THREAD

**Issue by 11721206** [kan-bayashi/ParallelWaveGAN#79]
![image](https://user-images.githubusercontent.com/19368412/74935602-7ca50700-5423-11ea-8c90-721477906c7f.png)
Hi, I just find when use Parallel_WaveGAN to synthesize, the spectrum will be not continus. my config file is from ljspeech/*v1.yaml. Is there any suggestions for my problem? thank you

**Comment by kan-bayashi** [comment]
Could you show the input fbank corresponding to that part?

**Comment by 11721206** [comment]
![image](https://user-images.githubusercontent.com/19368412/75085145-35bd2b80-5561-11ea-85d9-54b48d041937.png)
When I use higher steps Parallel_WaveGAN, this disappears, but some others appears. Is there soulution to avoid this ? thanks.

**Comment by kan-bayashi** [comment]
> When I use higher steps Parallel_WaveGAN, this disappears

You mean the model trained with more iterations? If so, you can continue to train to avoid this error.
Another choice is the use of large kernel_size in the generator (e.g. 5). This may lead to more natural sound.
