### ISSUE TITLE
data_download script in CSMSC

### ISSUE THREAD

**Issue by vjdtao** [kan-bayashi/ParallelWaveGAN#82]
I'd like to report that the shell script csmsc/voc1/local/data_download.sh breaks at line 24 with an error
`find: ‘CSMSC/PhoneLabeling’: No such file or directory`

I removed `CSMSC/`, and the script works.

**Comment by kan-bayashi** [comment]
Hi @vjdtao, thank you for your report!
I will fix it in #83.
