### ISSUE TITLE
The use of the .h5 format is hard-coded into egs/*/voc1/run.sh

### ISSUE THREAD

**Issue by matwhill** [kan-bayashi/ParallelWaveGAN#87]
For example:
https://github.com/kan-bayashi/ParallelWaveGAN/blob/172e40b7741b7e22d6a0c6bb4fa8898624374e41/egs/ljspeech/voc1/run.sh#L98

Whilst setting up an example using the .npy format, this causes tricky-to-catch errors.
I appreciate that reading the yaml config into bash is awkward, so perhaps a bash variable, or even a comment could aid the user?

:)

**Comment by kan-bayashi** [comment]
@matwhill Thank you for your report!
I will fix it in #88.

**Comment by kan-bayashi** [comment]
Fixed #88.
